Repository tomusborne/generateblocks, pull requests merged in 2021-07, with the labels that each got.

#69 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: priority: low, type: chore

#73 Prepare for 1.3.4 release
  package.json
  plugin.php
  readme.txt
Labels: type: chore

#80 wp-editor should not be enqueued in the new widget editor
  includes/general.php
Labels: priority: high, type: bug

#81 Update npm packages
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.css
  dist/dashboard.js
  package.json
  src/blocks/headline/markformat.js
Labels: type: chore

#82 Fix Cannot read property '__experimentalGetPreviewDeviceType' of null
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button-container/edit.js
  src/blocks/button/edit.js
  src/blocks/container/edit.js
  src/blocks/grid/edit.js
  src/blocks/headline/edit.js
Labels: type: bug

#83 Error when editing widget in the customizer
  includes/class-enqueue-css.php
Labels: priority: medium, type: bug

#85 Prepare 1.3.5
  package.json
  plugin.php
  readme.txt
Labels: type: chore

#86 Release 1.3.5
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.css
  dist/dashboard.js
  includes/class-enqueue-css.php
  includes/general.php
  package.json
  plugin.php
  readme.txt
  src/blocks/button-container/edit.js
  src/blocks/button/edit.js
  src/blocks/container/edit.js
  src/blocks/grid/edit.js
  src/blocks/headline/edit.js
  src/blocks/headline/markformat.js
Labels: priority: high, type: chore

#77 Add js unit tests
  .github/workflows/js-ci.yml
  Gruntfile.js
  package.json
  src/components/unit-picker/test/index.js
Labels: priority: low, type: chore
