Repository tomusborne/generateblocks, pull requests merged in 2021-08, with the labels that each got.

#91 Remove container padding defaults
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-legacy-attributes.php
  includes/defaults.php
  includes/generate-css.php
  src/blocks/container/edit.js
Labels: type: feature, priority: critical

#93 Remove container and button gradient default values
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-legacy-attributes.php
  includes/defaults.php
  includes/generate-css.php
  src/blocks/button-container/block.js
  src/blocks/button/block.js
  src/blocks/button/edit.js
  src/blocks/container/block-controls.js
  src/blocks/container/block.js
  src/blocks/container/edit.js
  src/blocks/grid/block.js
  src/blocks/grid/edit.js
  src/blocks/headline/block.js
  src/blocks/headline/element-icons.js
  src/components/gradient/index.js
  src/dashboard.js
  src/utils/hex-to-rgba/index.js
Labels: type: feature, priority: critical

#96 Remove select grid button
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/block-controls.js
Labels: type: feature

#95 Remove keepPlaceholderOnFocus
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button/edit.js
  src/blocks/headline/edit.js
Labels: type: bug, priority: low

#92 Remove grid item width defaults
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-legacy-attributes.php
  includes/defaults.php
  includes/generate-css.php
  src/blocks/container/edit.js
  src/blocks/grid/edit.js
Labels: type: feature, priority: critical

#61 Allow empty strings in Container padding
  dist/blocks.asset.php
  dist/blocks.js
  includes/defaults.php
  src/blocks/grid/edit.js
  src/components/dimensions/index.js
Labels: type: feature, priority: critical

#101 Bump version
  package.json
  plugin.php
Labels: type: chore

#98 Add custom range control
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/edit.js
  src/components/range-control/editor.scss
  src/components/range-control/index.js
Labels: type: feature, priority: high

#99 Fix wasBlockJustInserted when adding grid items
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/attributes.js
  src/blocks/container/edit.js
  src/blocks/grid/edit.js
  src/utils/was-block-just-inserted/index.js
Labels: type: bug, priority: high

#105 Only migrate grid item width if items are in a grid
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/edit.js
Labels: type: bug, priority: critical

#106 Allow zero values for minHeight on devices
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/edit.js
Labels: type: bug, priority: medium

#75 Remove default attributes
  .eslintrc.json
  .github/workflows/js-ci.yml
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  includes/class-legacy-attributes.php
  includes/defaults.php
  includes/functions.php
  includes/general.php
  includes/generate-css.php
  plugin.php
  src/blocks/button-container/block.js
  src/blocks/button/block.js
  src/blocks/button/edit.js
  src/blocks/container/attributes.js
  src/blocks/container/block-controls.js
  src/blocks/container/block.js
  src/blocks/container/edit.js
  src/blocks/grid/attributes.js
  src/blocks/grid/block.js
  src/blocks/grid/edit.js
  src/blocks/headline/block.js
  src/blocks/headline/element-icons.js
  src/components/dimensions/index.js
  src/components/gradient/index.js
  src/components/range-control/editor.scss
  src/components/range-control/index.js
  src/dashboard.js
  src/utils/check-block-version/index.js
  src/utils/hex-to-rgba/index.js
  src/utils/was-block-just-inserted/index.js
Labels: type: feature, priority: critical
