Repository tomusborne/generateblocks, pull requests merged in 2021-09, with the labels that each got.

#108 Disable grid item width options when using flex-basis
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/edit.js
  src/components/range-control/index.js
  src/shared/editor.scss
Labels: type: feature

#107 Update changelog for 1.4.0
  readme.txt
Labels: type: chore

#109 Check for empty uniqueId in wasBlockJustInserted
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button/edit.js
  src/blocks/container/attributes.js
  src/blocks/container/edit.js
  src/blocks/grid/edit.js
  src/utils/was-block-just-inserted/index.js
Labels: type: bug, priority: critical

#111 Prevent grid item zero values or values that start with zero
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/edit.js
  src/components/range-control/editor.scss
Labels: type: feature

#110 Add reset button to flex options
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/edit.js
  src/shared/editor.scss
  src/utils/get-icon/index.js
Labels: type: feature, priority: medium

#114 Improve selection of empty Container block
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/edit.js
  src/blocks/container/editor.scss
Labels: type: feature

#113 Add new block on Enter key in Headline block
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/headline/edit.js
Labels: type: feature, priority: medium

#115 Fix Buttons alignment in the editor
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/blocks/button-container/css/main.js
  src/blocks/button-container/css/mobile.js
  src/blocks/button-container/css/tablet.js
Labels: type: bug, priority: medium

#117 Add justify-content to buttons wrapper
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button-container/css/main.js
  src/blocks/button-container/css/mobile.js
  src/blocks/button-container/css/tablet.js
Labels: type: bug, priority: critical

#118 Improve Container block appender
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/edit.js
  src/blocks/container/editor.scss
Labels: type: bug, priority: critical

#119 Disable default container appender
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/edit.js
Labels: type: feature

#120 Fix error when using grid item width slider
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/edit.js
Labels: type: bug, priority: critical

#121 Improve empty container appender
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.js
  package.json
  src/blocks/container/css/main.js
  src/blocks/container/edit.js
  src/blocks/container/editor.scss
Labels: type: feature, priority: critical

#122 Fix container tag name accepting any value
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-render-blocks.php
  readme.txt
  src/blocks/container/edit.js
Labels: type: bug, priority: medium

#123 Check for opacity value before clearing
  dist/blocks.asset.php
  dist/blocks.js
  src/components/color-picker/index.js
Labels: type: bug, priority: medium

#124 Add background color to appender
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.js
  package.json
  src/blocks/container/css/main.js
  src/blocks/container/editor.scss
Labels: type: feature, priority: critical

#125 Release 1.4.0 alpha.2
  package.json
  plugin.php
  readme.txt
Labels: type: chore

#126 Add protocol to Google fonts request
  includes/functions.php
Labels: type: bug, priority: high

#127 Add hash to hex values missing it
  dist/blocks.asset.php
  dist/blocks.js
  src/components/color-picker/index.js
Labels: type: bug, priority: high

#128 Implement withUniqueId HOC component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.css
  dist/dashboard.js
  src/blocks/button-container/block.js
  src/blocks/button-container/edit.js
  src/blocks/button/block.js
  src/blocks/button/edit.js
  src/blocks/container/block.js
  src/blocks/container/edit.js
  src/blocks/grid/block.js
  src/blocks/grid/edit.js
  src/blocks/headline/block.js
  src/blocks/headline/edit.js
  src/hoc/test/withUniqueId.js
  src/hoc/withUniqueId.js
  src/utils/get-all-unique-ids/index.js
  src/utils/get-editor-blocks.js
Labels: type: feature, priority: high

#130 Split headline component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.css
  dist/dashboard.js
  src/blocks/headline/components/BlockControls.js
  src/blocks/headline/components/InspectorControls.js
  src/blocks/headline/components/ToolbarGroup.js
  src/blocks/headline/edit.js
  src/hoc/test/withUniqueId.js
  src/hoc/withUniqueId.js
Labels: type: feature, priority: high

#131 Release 1.4.0 beta.1
  package.json
  plugin.php
  readme.txt
Labels: type: chore
