Repository tomusborne/generateblocks, pull requests merged in 2021-10, with the labels that each got.

#132 Split Grid block components
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/grid/components/BlockControls.js
  src/blocks/grid/components/ComponentCSS.js
  src/blocks/grid/components/InspectorAdvancedControls.js
  src/blocks/grid/components/InspectorControls.js
  src/blocks/grid/edit.js
Labels: type: chore, priority: high

#133 Make the grid block functional
  dist/blocks.asset.php
  dist/blocks.js
  dist/dashboard.asset.php
  src/blocks/grid/components/BlockControls.js
  src/blocks/grid/components/LayoutSelector.js
  src/blocks/grid/edit.js
Labels: type: feature, priority: critical

#134 Improve empty container visibility
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/edit.js
  src/blocks/container/editor.scss
Labels: type: feature, priority: critical

#136 Fix align support in block themes
  dist/blocks.asset.php
  dist/blocks.js
  dist/dashboard.asset.php
  includes/general.php
  src/blocks/container/block-controls.js
Labels: type: bug, priority: high

#138 Show css variable color in palette
  dist/blocks.asset.php
  dist/blocks.js
  src/components/color-picker/index.js
Labels: type: feature, priority: critical

#143 1.4.0-rc.2
  package.json
  plugin.php
Labels: type: chore
