Repository tomusborne/generateblocks, pull requests merged in 2021-11, with the labels that each got.

#159 Make Grid block a functional component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  src/blocks/button-container/block.js
  src/blocks/button-container/edit.js
  src/blocks/button/block.js
  src/blocks/button/edit.js
  src/blocks/container/block.js
  src/blocks/container/edit.js
  src/blocks/grid/components/BlockControls.js
  src/blocks/grid/components/ComponentCSS.js
  src/blocks/grid/components/InspectorAdvancedControls.js
  src/blocks/grid/components/InspectorControls.js
  src/blocks/grid/components/LayoutSelector.js
  src/blocks/grid/edit.js
  src/blocks/headline/block.js
  src/blocks/headline/components/BlockControls.js
  src/blocks/headline/components/InspectorControls.js
  src/blocks/headline/components/ToolbarGroup.js
  src/blocks/headline/edit.js
  src/hoc/index.js
  src/hoc/test/withUniqueId.js
  src/hoc/withGridLegacyMigration.js
  src/hoc/withUniqueId.js
  src/hooks/index.js
  src/hooks/useDeviceType.js
  src/hooks/useInnerBlocksCount.js
  src/utils/get-all-unique-ids/index.js
  src/utils/get-editor-blocks.js
Labels: type: feature, priority: critical

#147 Headline functional
  dist/blocks.asset.php
  dist/blocks.js
  dist/dashboard.asset.php
  src/blocks/grid/components/InspectorAdvancedControls.js
  src/blocks/grid/edit.js
  src/blocks/headline/components/ComponentCSS.js
  src/blocks/headline/components/GoogleFontLink.js
  src/blocks/headline/components/InspectorControls.js
  src/blocks/headline/edit.js
  src/blocks/headline/save.js
  src/components/html-anchor/index.js
  src/components/icon-wrapper/index.js
  src/components/icon-wrapper/test/__snapshots__/index.js.snap
  src/components/icon-wrapper/test/index.js
  src/dashboard.js
  src/hoc/withGridLegacyMigration.js
  src/hooks/index.js
  src/hooks/useDeviceType.js
Labels: type: feature, priority: critical

#160 Enable GitHub actions
  .github/workflows/js-ci.yml
  src/components/unit-picker/test/index.js
Labels: type: chore, priority: low

#161 Make Button block a functional component
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button/block.js
  src/blocks/button/components/BlockControls.js
  src/blocks/button/components/ComponentCSS.js
  src/blocks/button/components/InspectorAdvancedControls.js
  src/blocks/button/components/InspectorControls.js
  src/blocks/button/edit.js
  src/blocks/button/save.js
  src/blocks/headline/edit.js
  src/components/google-font-link/index.js
  src/hoc/index.js
  src/hoc/withButtonLegacyMigration.js
Labels: type: feature, priority: critical

#162 Make Button Container block a functional component
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button-container/block.js
  src/blocks/button-container/components/BlockAppender.js
  src/blocks/button-container/components/BlockControls.js
  src/blocks/button-container/components/ComponentCSS.js
  src/blocks/button-container/components/InspectorControls.js
  src/blocks/button-container/edit.js
  src/hoc/index.js
  src/hoc/withButtonContainerLegacyMigration.js
Labels: type: feature, priority: critical

#163 Make Container block a functional component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/block.js
  src/blocks/container/components/BlockControls.js
  src/blocks/container/components/ComponentCSS.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/components/ShapeDividers.js
  src/blocks/container/edit.js
  src/hoc/index.js
  src/hoc/withContainerLegacyMigration.js
Labels: type: feature, priority: critical

#168 Move button url options to toolbar
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.js
  package.json
  src/blocks/button/components/BlockControls.js
  src/blocks/button/edit.js
  src/blocks/button/editor.scss
  src/components/url-input/editor.scss
  src/components/url-input/index.js
Labels: type: feature, priority: critical

#169 Use apiVersion: 2 in Buttons
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  plugin.php
  readme.txt
  src/blocks/button-container/block.js
  src/blocks/button-container/edit.js
  src/blocks/button-container/editor.scss
  src/blocks/button/block.js
  src/blocks/button/edit.js
  src/blocks/button/editor.scss
  src/blocks/button/save.js
Labels: type: feature, priority: critical

#171 Use apiVersion: 2 in Headline
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/headline/block.js
  src/blocks/headline/edit.js
  src/blocks/headline/editor.scss
  src/blocks/headline/save.js
Labels: type: feature, priority: critical

#170 Improve grid column horizontal gap
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/block.js
  src/blocks/container/components/GridItem.js
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/container/edit.js
  src/blocks/grid/block.js
  src/blocks/grid/css/main.js
  src/blocks/grid/css/mobile.js
  src/blocks/grid/css/tablet.js
  src/blocks/grid/edit.js
  src/blocks/grid/editor.scss
Labels: type: feature, priority: critical

#172 Keep isGrid and gridId current
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/components/InspectorControls.js
Labels: type: feature, priority: high

#173 Fix query grid selectors
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/grid/components/QueryLoopRenderer.js
  src/blocks/grid/components/QueryWrapper.js
  src/blocks/grid/css/main.js
  src/blocks/grid/css/mobile.js
  src/blocks/grid/css/tablet.js
  src/blocks/grid/edit.js
  src/blocks/grid/editor.scss
Labels: type: bug, priority: critical

#175 Create query loop block
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/class-render-blocks.php
  includes/functions.php
  src/blocks.js
  src/blocks/container/block-controls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/grid/attributes.js
  src/blocks/grid/components/query-loop/InspectorControls.js
  src/blocks/grid/edit.js
  src/blocks/query-loop/attributes.js
  src/blocks/query-loop/block.js
  src/blocks/query-loop/components/InspectorControls.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/blocks/query-loop/components/QueryWrapper.js
  src/blocks/query-loop/hoc/withQueryLoop.js
  src/blocks/query-loop/hooks/useQueryLoopData.js
Labels: type: feature, priority: critical

#174 Dynamic content framework
  dist/blocks.asset.php
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.js
  dist/style-blocks.css
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  package.json
  plugin.php
  src/blocks/headline/block.js
  src/blocks/headline/components/dynamic-content/DynamicContentRenderer.js
  src/blocks/headline/components/dynamic-content/InspectorControls.js
  src/blocks/headline/components/dynamic-content/attributes.js
  src/blocks/headline/components/dynamic-content/components/SelectPost.js
  src/blocks/headline/components/dynamic-content/components/SelectPostType.js
  src/blocks/headline/components/dynamic-content/components/SelectSource.js
  src/blocks/headline/components/dynamic-content/hoc/withDynamicContent.js
  src/blocks/headline/components/dynamic-content/hooks/useDynamicContent.js
  src/blocks/headline/components/dynamic-content/hooks/usePostTypeRecords.js
  src/blocks/headline/components/dynamic-content/hooks/usePostTypes.js
  src/blocks/headline/components/dynamic-content/inspector-controls/ContentTypeControl.js
  src/blocks/headline/components/dynamic-content/inspector-controls/DynamicSourceControl.js
  src/blocks/headline/components/dynamic-content/utils/getContent.js
  src/blocks/headline/edit.js
  src/components/advanced-select/index.js
  src/components/advanced-select/style.scss
  src/components/icon-picker/index.js
  src/utils/filter-attributes/index.js
  src/utils/filter-attributes/test/index.js
Labels: type: feature, priority: critical
