Repository tomusborne/generateblocks, pull requests merged in 2022-03, with the labels that each got.

#231 Loop pagination
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-query-loop.php
  includes/class-render-blocks.php
  plugin.php
  src/blocks.js
  src/blocks/button-container/attributes.js
  src/blocks/button-container/block.js
  src/blocks/button-container/edit.js
  src/blocks/button/block.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/grid/css/main.js
  src/blocks/grid/css/mobile.js
  src/blocks/grid/css/tablet.js
  src/blocks/grid/edit.js
  src/blocks/grid/editor.scss
  src/blocks/headline/block.js
  src/blocks/post-template/LoopRenderer.js
  src/blocks/post-template/block.json
  src/blocks/post-template/edit.js
  src/blocks/post-template/index.js
  src/blocks/post-template/utils.js
  src/blocks/query-loop/block.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/blocks/query-loop/components/QueryWrapper.js
  src/blocks/query-loop/components/query-loop-renderer/index.js
  src/blocks/query-loop/editor.scss
  src/blocks/query-loop/hoc/withQueryLoop.js
  src/blocks/query-loop/hooks/useQueryLoopData.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
  src/extend/dynamic-content/utils/getContentTypeLabel.js
Labels: type: feature, priority: critical

#232 Improve query appender
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/class-query-loop.php
  includes/functions.php
  includes/generate-css.php
  src/blocks/post-template/LoopRenderer.js
  src/blocks/post-template/edit.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/blocks/query-loop/editor.scss
Labels: type: feature, priority: critical

#233 Implement pagination numbers
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  src/blocks/button-container/components/BlockControls.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
  src/extend/dynamic-content/utils/getContent.js
  src/extend/dynamic-content/utils/getContentTypeLabel.js
Labels: type: feature, priority: critical

#234 Add dynamic background image
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  includes/functions.php
  includes/general.php
  includes/generate-css.php
  src/blocks/container/block.js
  src/blocks/container/components/ContainerContentRenderer.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/css/main.js
  src/blocks/container/edit.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/components/SelectSource.js
  src/extend/dynamic-content/hooks/useDynamicContent.js
  src/extend/dynamic-content/hooks/usePostRecord.js
  src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
  src/extend/dynamic-content/utils/getContent.js
  src/utils/get-background-image-url/index.js
  src/utils/get-background-image/index.js
Labels: type: feature, priority: critical

#238 Remove empty button container
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
Labels: type: bug, priority: critical

#235 Fix pagination alignment
  includes/class-query-loop.php
Labels: type: bug, priority: critical

#241 Add default container width option
  dist/dashboard.asset.php
  dist/dashboard.css
  dist/dashboard.js
  includes/class-rest.php
  includes/class-settings.php
  includes/defaults.php
  src/dashboard.js
  src/dashboard.scss
Labels: type: feature

#242 Add new color component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  dist/dashboard.css
  dist/dashboard.js
  package.json
  src/blocks/button/components/InspectorControls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/headline/components/InspectorControls.js
  src/components/color-group/editor.scss
  src/components/color-group/index.js
  src/components/color-picker/editor.scss
  src/components/color-picker/index.js
Labels: type: feature

#243 Refactor dimensions component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/button-container/components/InspectorControls.js
  src/blocks/button/components/InspectorControls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/headline/components/InspectorControls.js
  src/components/dimensions-group/index.js
  src/components/dimensions/editor.scss
  src/components/dimensions/index.js
  src/utils/get-responsive-placeholder/index.js
Labels: type: feature

#244 Add new number component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/button/components/InspectorControls.js
  src/blocks/grid/components/InspectorControls.js
  src/blocks/headline/components/InspectorControls.js
  src/components/number-control/editor.scss
  src/components/number-control/index.js
  src/components/typography/index.js
  src/components/unit-picker/index.js
Labels: type: feature

#252 Fix block breaking when query source changes
  dist/blocks.asset.php
  dist/blocks.js
  src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
Labels: type: bug, priority: critical

#250 Add styling to image block
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/blocks/image/block.json
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  includes/defaults.php
  includes/functions.php
  includes/generate-css.php
  src/blocks/image/block.json
  src/blocks/image/components/AnchorTag.js
  src/blocks/image/components/BlockControls.js
  src/blocks/image/components/ComponentCSS.js
  src/blocks/image/components/Image.js
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/image/components/ImagePlaceholder.js
  src/blocks/image/components/InspectorControls.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/blocks/image/css/desktop.js
  src/blocks/image/css/main.js
  src/blocks/image/css/mobile.js
  src/blocks/image/css/tablet-only.js
  src/blocks/image/css/tablet.js
  src/blocks/image/edit.js
  src/blocks/image/editor.scss
  src/blocks/image/index.js
  src/blocks/image/save.js
  src/components/dimensions/attributes.js
  src/components/link-control/index.js
  src/components/media-upload-control/index.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/hooks/usePostRecord.js
  src/extend/dynamic-content/utils/getContent.js
  src/hoc/withResponsiveTabs.js
Labels: type: feature

#247 Improve panel memory
  dist/blocks.asset.php
  dist/blocks.js
  dist/dashboard.asset.php
  package-lock.json
  package.json
  src/components/panel-area/index.js
Labels: type: feature

#248 Add memory to custom input state
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/components/number-control/editor.scss
  src/components/number-control/index.js
Labels: type: feature

#253 Add dimension options to image block
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/blocks/image/block.json
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  includes/defaults.php
  includes/generate-css.php
  package-lock.json
  package.json
  src/blocks/image/block.json
  src/blocks/image/components/Image.js
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/blocks/image/css/main.js
  src/blocks/image/css/mobile.js
  src/blocks/image/css/tablet.js
  src/blocks/image/edit.js
  src/blocks/image/editor.scss
  src/blocks/image/save.js
  src/components/number-control/editor.scss
  src/components/number-control/index.js
  src/components/panel-area/index.js
  src/components/unit-picker/index.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/utils/getContent.js
  src/utils/get-attribute/index.js
  src/utils/get-background-image-url/index.js
  src/utils/get-image-sizes/index.js
  src/utils/get-media-url/index.js
Labels: type: feature

#246 Refactor typography component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  src/blocks/button/components/InspectorControls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/headline/components/InspectorControls.js
  src/components/typography/editor.scss
  src/components/typography/index.js
Labels: type: feature

#254 Fix bug on changing dynamic source
  dist/blocks.asset.php
  dist/blocks.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
Labels: type: bug, priority: critical

#256 Add author avatar and post meta for image dynamic types
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/image/components/ImagePlaceholder.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/blocks/image/edit.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
  src/extend/dynamic-content/inspector-controls/PostMetaControl.js
  src/extend/dynamic-content/utils/getContent.js
Labels: type: feature, priority: high

#264 Make device buttons sticky
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  src/components/responsive-tabs/editor.scss
  src/components/responsive-tabs/index.js
Labels: type: feature

#266 Improve container width label
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/components/InspectorControls.js
Labels: type: feature

#270 Check for false number values before parsing
  dist/blocks.asset.php
  dist/blocks.js
  src/components/number-control/index.js
Labels: type: bug, priority: low

#271 Fix image floating issue in editor
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/image/editor.scss
  src/components/root-element/index.js
Labels: type: bug, priority: critical

#272 Fix outer container width in editor
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/css/main.js
Labels: type: bug, priority: critical

#273 Improve shouldRebuildCSS
  dist/blocks.asset.php
  dist/blocks.js
  src/utils/should-rebuild-css/index.js
Labels: type: bug, priority: critical

#276 Add new block icons
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/button-container/block.js
  src/blocks/button-container/components/BlockControls.js
  src/blocks/button/components/BlockControls.js
  src/blocks/post-template/index.js
  src/blocks/query-loop/block.js
  src/shared/editor.scss
  src/utils/get-icon/index.js
Labels: type: feature
