Repository tomusborne/generateblocks, pull requests merged in 2022-09, with the labels that each got.

#679 Fix: Duplicate CSS when using external file
  includes/blocks/class-button-container.php
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-grid.php
  includes/blocks/class-headline.php
  includes/blocks/class-image.php
  includes/class-enqueue-css.php
  includes/functions.php
Labels: bug

#683 Fix: Missing CSS when do_blocks is ran early
  includes/blocks/class-button-container.php
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-grid.php
  includes/blocks/class-headline.php
  includes/blocks/class-image.php
  includes/class-enqueue-css.php
  includes/functions.php
Labels: bug

#676 Update package versions
  package-lock.json
  package.json
Labels: refactoring

#691 Feature: Remove inside div from Container block
  includes/blocks/class-container.php
  includes/class-do-css.php
  includes/functions.php
  includes/general.php
  src/blocks/container/attributes.js
  src/blocks/container/block.js
  src/blocks/container/components/ContainerContentRenderer.js
  src/blocks/container/components/FlexControls.js
  src/blocks/container/components/GridItemWidthControl.js
  src/blocks/container/components/InsideContainer.js
  src/blocks/container/components/InspectorAdvancedControls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/components/LayoutControls.js
  src/blocks/container/components/LegacyLayoutControls.js
  src/blocks/container/components/MigrateInnerContainer.js
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/container/edit.js
  src/blocks/container/editor.scss
  src/components/dimensions/editor.scss
  src/components/dimensions/index.js
  src/components/unit-control/editor.scss
  src/components/unit-control/index.js
  src/hoc/withContainerLegacyMigration.js
  src/utils/get-icon/index.js
Labels: feature

#695 Fix: Container styles being overwritten when multi-selected
  src/components/color-picker/index.js
Labels: bug

#694 Feature: Add block appender filters
  includes/blocks/class-button-container.php
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-grid.php
  includes/blocks/class-headline.php
  includes/blocks/class-image.php
  src/blocks/button-container/components/BlockControls.js
  src/blocks/button-container/edit.js
  src/blocks/button/components/BlockControls.js
  src/blocks/button/components/ButtonContentRenderer.js
  src/blocks/button/edit.js
  src/blocks/button/save.js
  src/blocks/container/components/BlockAppender.js
  src/blocks/container/components/ContainerContentRenderer.js
  src/components/icon-picker/index.js
Labels: feature

#698 Feature: Allow Buttons outside of the Button Container block
  includes/blocks/class-button.php
  src/blocks/button-container/block.js
  src/blocks/button/attributes.js
  src/blocks/button/block.js
  src/blocks/button/components/BlockControls.js
  src/blocks/button/components/ButtonContentRenderer.js
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/button/edit.js
  src/blocks/button/editor.scss
  src/hoc/withButtonLegacyMigration.js
Labels: feature

#699 Fix: Dynamic content class conflicts
  includes/blocks/class-button.php
  includes/blocks/class-headline.php
  includes/class-dynamic-content.php
Labels: bug

#700 Fix: Missing legacy alpha color slider in gradient component
  readme.txt
  src/components/gradient/index.js
Labels: bug

#703 Fix php 8 deprecation warning
  includes/functions.php
Labels: bug

#706 Feature: Allow non-numerical values in unit control
  src/components/unit-control/index.js
Labels: feature
