Repository tomusborne/generateblocks, pull requests merged in 2022-04, with the labels that each got.

#281 Improve button container
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/button-container/components/BlockAppender.js
  src/blocks/button-container/components/BlockControls.js
  src/blocks/button-container/edit.js
  src/blocks/button-container/editor.scss
  src/blocks/button/editor.scss
Labels: type: feature, priority: medium

#287 Add visible labels to Dimensions component
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/components/dimensions/editor.scss
  src/components/dimensions/index.js
Labels: type: feature, priority: critical

#288 Add computed placeholders
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button/components/InspectorControls.js
  src/blocks/button/edit.js
  src/blocks/headline/components/InspectorControls.js
  src/blocks/headline/edit.js
  src/components/dimensions-group/index.js
  src/components/dimensions/index.js
  src/components/number-control/index.js
  src/components/typography/index.js
Labels: type: feature, priority: critical

#284 Use Grid block as Post Template
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/blocks/post-template/block.json
  includes/class-dynamic-content.php
  includes/class-query-loop.php
  includes/class-render-blocks.php
  includes/functions.php
  includes/generate-css.php
  src/blocks.js
  src/blocks/button-container/block.js
  src/blocks/button-container/edit.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/edit.js
  src/blocks/grid/attributes.js
  src/blocks/grid/components/InspectorControls.js
  src/blocks/grid/edit.js
  src/blocks/post-template/block.json
  src/blocks/post-template/edit.js
  src/blocks/post-template/index.js
  src/blocks/query-loop/attributes.js
  src/blocks/query-loop/block.js
  src/blocks/query-loop/components/InspectorControls.js
  src/blocks/query-loop/components/LoopRenderer.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/edit.js
  src/blocks/query-loop/editor.scss
  src/blocks/query-loop/hoc/withQueryLoop.js
  src/hoc/withResponsiveTabs.js
  src/shared/editor.scss
Labels: type: feature, priority: critical

#285 Add Query Loop templates
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/query-loop/components/LayoutSelector.js
  src/blocks/query-loop/edit.js
  src/blocks/query-loop/editor.scss
  src/blocks/query-loop/templates.js
Labels: type: feature, priority: critical

#289 Move pagination appender to BlockControls
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/query-loop/components/BlockControls.js
  src/blocks/query-loop/edit.js
  src/utils/get-icon/index.js
Labels: type: feature

#278 Add inherit query from template option
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  src/blocks/button/block.js
  src/blocks/query-loop/attributes.js
  src/blocks/query-loop/block.js
  src/blocks/query-loop/components/InspectorControls.js
Labels: type: feature, priority: critical

#291 Fix number preset highlights
  dist/blocks.asset.php
  dist/blocks.js
  src/components/number-control/index.js
Labels: type: bug, priority: critical

#292 Fix dynamic links for featured images
  includes/class-dynamic-content.php
Labels: type: bug, priority: critical

#295 Add single image option to dynamic links
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/image/save.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
Labels: type: feature, priority: critical

#293 Add excerpt options
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/general.php
  src/components/number-control/index.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/inspector-controls/ExcerptControl.js
  src/extend/dynamic-content/utils/getContent.js
Labels: type: feature

#297 Remove edit block as html from our dynamic blocks
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button-container/block.js
  src/blocks/container/block.js
  src/blocks/grid/block.js
Labels: type: bug, priority: medium

#298 Add debounced state hook for the headline and button richtext component
  dist/blocks.asset.php
  dist/blocks.js
  package-lock.json
  package.json
  src/blocks/button/components/ButtonContentRenderer.js
  src/blocks/headline/components/HeadlineContentRenderer.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
  src/components/debounced-text-control/index.js
  src/extend/dynamic-content/inspector-controls/ExcerptControl.js
  src/hooks/useDebounceState.js
Labels: type: feature, priority: medium

#300 Query code cleanup
  dist/blocks.asset.php
  dist/blocks.js
  package-lock.json
  src/blocks/button/block.js
  src/blocks/container/block-controls.js
  src/blocks/headline/block.js
  src/blocks/image/components/AnchorTag.js
  src/blocks/image/components/ImagePlaceholder.js
  src/blocks/image/edit.js
  src/blocks/query-loop/components/LoopRenderer.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/components/icon-picker/index.js
  src/components/link-control/index.js
  src/components/media-upload-control/index.js
  src/components/media-upload-control/styles.scss
  src/hooks/useDebounceState.js
  src/utils/get-icon/index.js
Labels: priority: critical

#301 Query code cleanup
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/block-controls.js
  src/components/icon-picker/index.js
Labels: type: bug, priority: critical

#308 Fix query grid
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/query-loop/editor.scss
  src/blocks/query-loop/templates.js
Labels: type: bug, priority: critical

#309 Fix query pagination
  includes/class-render-blocks.php
Labels: type: bug, priority: critical

#310 Fix avatar class
  includes/class-dynamic-content.php
Labels: type: bug, priority: critical

#311 Fix dynamic image sizing
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/image/components/ImagePlaceholder.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
Labels: type: bug, priority: critical

#316 Fix useDeviceType hook when sync preview is disabled
  dist/blocks.asset.php
  dist/blocks.js
  src/hooks/useDeviceType.js
Labels: type: bug, priority: low

#317 Fix image dimensions PHP notices
  includes/defaults.php
Labels: type: bug, priority: critical, block: Image

#315 Add border color to image block
  dist/blocks.asset.php
  dist/blocks.js
  dist/blocks/image/block.json
  src/blocks/image/block.json
  src/blocks/image/components/InspectorControls.js
Labels: type: feature, priority: critical, block: Image

#318 Fix dynamic button icon location
  includes/class-render-blocks.php
Labels: type: bug, priority: critical

#319 Fix empty image saving
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/image/save.js
Labels: type: bug, priority: critical, block: Image

#320 Fix missing dynamic image link
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
Labels: type: bug, priority: critical, block: Image

#321 Change caption icon
  dist/blocks.asset.php
  dist/blocks.js
  src/utils/get-icon/index.js
Labels: type: feature, block: Image

#325 Fix offset when WP_Query is paginated
  includes/class-query-loop.php
Labels: type: bug, priority: high, block: Query loop

#327 Improve dynamic image placeholders
  assets/images/image-placeholder.png
  assets/images/square-image-placeholder.png
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/general.php
  src/blocks/image/components/ImagePlaceholder.js
  src/blocks/image/editor.scss
Labels: type: feature, priority: critical, block: Image

#330 Fix empty raw excerpts in editor
  dist/blocks.asset.php
  dist/blocks.js
  src/extend/dynamic-content/utils/getContent.js
Labels: type: bug, priority: high, block: Dynamic content

#331 Add caption list view label
  dist/blocks.asset.php
  dist/blocks.js
  src/extend/dynamic-content/utils/getContentTypeLabel.js
Labels: type: feature, block: Image

#332 Show blocks even if empty dynamic link
  includes/class-render-blocks.php
Labels: block: Dynamic content

#333 Only set query attributes if needed
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/query-loop/components/InspectorControls.js
Labels: type: bug, priority: critical, block: Query loop

#342 Improve dynamic image dimensions
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/blocks/image/edit.js
  src/blocks/image/editor.scss
  src/extend/dynamic-content/InspectorControls.js
Labels: type: bug, priority: critical, block: Image

#334 Fix color palette error
  dist/blocks.asset.php
  dist/blocks.js
  readme.txt
  src/components/color-picker/index.js
Labels: type: bug, priority: critical

#347 Fix endless loops by not rendering excerpts within themselves
  includes/class-dynamic-content.php
Labels: priority: critical, block: Dynamic content

#345 Change isDynamicContent attribute name
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  includes/functions.php
  src/blocks/button/components/BlockControls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/css/main.js
  src/blocks/image/components/Image.js
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/image/components/ImagePlaceholder.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/blocks/image/edit.js
  src/blocks/image/save.js
  src/blocks/query-loop/components/BlockControls.js
  src/blocks/query-loop/templates.js
  src/components/link-control/index.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/hoc/withDynamicContent.js
  src/extend/dynamic-content/utils/getContentTypeLabel.js
  src/utils/get-background-image-url/index.js
  src/utils/get-background-image/index.js
  src/utils/get-dynamic-image/index.js
Labels: block: Dynamic content

#346 Change contentType attribute name
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  includes/functions.php
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/css/main.js
  src/blocks/headline/components/HeadlineContentRenderer.js
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/image/edit.js
  src/blocks/image/save.js
  src/blocks/query-loop/components/BlockControls.js
  src/blocks/query-loop/templates.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/components/SelectSource.js
  src/extend/dynamic-content/hoc/withContentLink.js
  src/extend/dynamic-content/hoc/withDynamicContent.js
  src/extend/dynamic-content/hooks/useDynamicContent.js
  src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
  src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
  src/extend/dynamic-content/utils/getContent.js
  src/extend/dynamic-content/utils/getContentTypeLabel.js
  src/utils/get-background-image-url/index.js
  src/utils/get-background-image/index.js
Labels: block: Dynamic content

#341 Image fixes and minor features
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  src/blocks/image/components/Image.js
  src/blocks/image/edit.js
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/components/SelectPostType.js
  src/extend/dynamic-content/hooks/useDynamicContent.js
  src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
  src/extend/dynamic-content/utils/applyContext.js
  src/extend/dynamic-content/utils/getContent.js
  src/utils/get-dynamic-image/index.js
Labels: type: feature, type: bug, priority: high, block: image

#351 Add image alignment options
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/blocks/image/block.json
  includes/class-dynamic-content.php
  includes/defaults.php
  includes/functions.php
  includes/generate-css.php
  phpcs.xml.dist
  src/blocks/image/block.json
  src/blocks/image/components/AlignmentControls.js
  src/blocks/image/components/BlockControls.js
  src/blocks/image/components/Image.js
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/image/css/main.js
  src/blocks/image/css/mobile.js
  src/blocks/image/css/tablet.js
  src/blocks/image/edit.js
  src/blocks/image/editor.scss
  src/blocks/image/save.js
  src/shared/editor.scss
Labels: type: feature, block: image

#356 Remove acf from the meta fields list
  dist/blocks.asset.php
  dist/blocks.js
  src/extend/dynamic-content/hooks/usePostRecord.js
  src/extend/dynamic-content/inspector-controls/PostMetaControl.js
  src/extend/dynamic-content/utils/getContent.js
Labels: block: dynamic-content

#357 Fix responsive previews
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button-container/components/ComponentCSS.js
  src/blocks/button/components/ComponentCSS.js
  src/blocks/container/components/ComponentCSS.js
  src/blocks/grid/components/ComponentCSS.js
  src/blocks/headline/components/ComponentCSS.js
  src/blocks/image/components/ComponentCSS.js
  src/hooks/useDeviceType.js
Labels: type: bug, priority: critical

#365 Add filter to fallback dynamic images
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  src/blocks/image/components/ImageContentRenderer.js
Labels: type: feature, block: dynamic-content

#363 Use block.json in dist folder to register
  includes/class-render-blocks.php
Labels: block: image, type: refactoring

#366 Add $block to attribute functions
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  includes/functions.php
Labels: type: feature

#371 Fix missing dynamic Container backgrounds
  dist/blocks.asset.php
  dist/blocks.js
  src/utils/get-dynamic-image/index.js
Labels: type: bug, priority: critical, block: dynamic-content

#372 Add transforms for image block
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/image/index.js
  src/blocks/image/transforms.js
Labels: type: feature, block: image

#369 Improve usePostRecord hook
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/headline/components/HeadlineContentRenderer.js
  src/extend/dynamic-content/hooks/useDynamicContent.js
  src/extend/dynamic-content/hooks/usePostRecord.js
  src/extend/dynamic-content/inspector-controls/AuthorMetaControl.js
  src/extend/dynamic-content/inspector-controls/PostMetaControl.js
Labels: priority: critical, block: dynamic-content

#373 Update Dashboard content
  assets/css/dashboard.css
  dist/blocks.asset.php
  dist/blocks/image/block.json
  includes/dashboard.php
  src/blocks/image/block.json
Labels: type: chore
