Repository tomusborne/generateblocks, pull requests merged in 2022-11, with the labels that each got.

#737 Feature: Add unit control presets
  src/components/unit-control/editor.scss
  src/components/unit-control/index.js
  src/extend/inspector-control/controls/layout/components/editor.scss
  src/extend/inspector-control/controls/sizing/components/MaxWidth.js
  src/extend/inspector-control/controls/sizing/index.js
  src/extend/inspector-control/index.js
  src/shared/editor.scss
Labels: feature

#749 Tweak: Clean up spacing attributes
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-headline.php
  includes/blocks/class-image.php
  includes/general.php
  src/blocks/container/attributes.js
Labels: refactoring

#752 Tweak: Merge gradient and background panels
  src/block-context/button.js
  src/block-context/container.js
  src/block-context/default.js
  src/block-context/index.js
  src/extend/inspector-control/controls/background-gradient/index.js
  src/extend/inspector-control/controls/background-panel/attributes.js
  src/extend/inspector-control/controls/background-panel/index.js
  src/extend/inspector-control/index.js
Labels: refactoring

#753 Tweak: Move device buttons above BlockCard
  src/components/responsive-tabs/index.js
  src/extend/inspector-control/controls/responsive-tabs/editor.scss
  src/extend/inspector-control/controls/responsive-tabs/index.js
  src/extend/inspector-control/index.js
  src/hoc/index.js
  src/hoc/withResponsiveTabs.js
Labels: feature

#739 Feature: Improve typography component
  package-lock.json
  package.json
  src/block-context/container.js
  src/block-context/default.js
  src/block-context/headline.js
  src/blocks/container/components/BlockControls.js
  src/blocks/container/edit.js
  src/blocks/headline/components/BlockControls.js
  src/components/advanced-select/index.js
  src/components/flex-control/editor.scss
  src/components/flex-control/index.js
  src/extend/inspector-control/controls/typography/components/alignment.js
  src/extend/inspector-control/controls/typography/components/font-family.js
  src/extend/inspector-control/controls/typography/components/text-transform.js
  src/extend/inspector-control/controls/typography/editor.scss
  src/extend/inspector-control/controls/typography/index.js
  src/extend/inspector-control/controls/typography/options.js
Labels: feature

#758 Feature: Add inner container button
  src/blocks/container/block-controls.js
  src/blocks/container/variations/index.js
  src/blocks/container/variations/section/index.js
Labels: feature

#763 Tweak: Remove block description from inspector controls
  src/extend/inspector-control/controls/responsive-tabs/editor.scss
Labels: refactoring

#734 Feature: Accordion block
  includes/blocks/class-accordion.php
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  package.json
  plugin.php
  src/accordion.js
  src/block-context/container.js
  src/block-context/index.js
  src/blocks.js
  src/blocks/button/attributes.js
  src/blocks/container/edit.js
  src/extend/accordion/attributes.js
  src/extend/accordion/components/AccordionTemplate.js
  src/extend/accordion/components/BlockAppender.js
  src/extend/accordion/components/ButtonInspectorControls.js
  src/extend/accordion/components/ContainerInspectorControls.js
  src/extend/accordion/edit.js
  src/extend/accordion/editor.scss
  src/extend/accordion/index.js
  src/utils/get-icon/index.js
Labels: feature

#762 Feature: Add text-align to Button block
  includes/blocks/class-button.php
  src/block-context/button.js
  src/blocks/button/components/BlockControls.js
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/button/editor.scss
  src/blocks/container/attributes.js
  src/blocks/headline/attributes.js
  src/extend/inspector-control/controls/typography/attributes.js
  src/hoc/withButtonLegacyMigration.js
Labels: feature

#764 Fix: setAttributes console log warning
  src/blocks/button/components/ButtonContentRenderer.js
Labels: bug

#768 Tweak: Migrate GPP Element inline option
  src/components/migrate-inner-container/utils.js
Labels: refactoring

#766 Add filter to control query loop posts cap in the editor
  includes/general.php
  src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
  src/blocks/query-loop/components/utils.js
Labels: feature

#771 Tweak: Remove icon vertical alignment
  src/extend/inspector-control/controls/icon/components/icon-alignment.js
  src/extend/inspector-control/controls/icon/components/icon-styles.js
  src/extend/inspector-control/controls/icon/index.js
Labels: bug

#774 Fix container anchor tag
  src/blocks/container/edit.js
Labels: bug

#767 Fix: get_the_excerpt notice with no source ID
  includes/class-dynamic-content.php
Labels: bug

#781 Refactor: Remove accordion block
  includes/blocks/class-accordion.php
  package.json
  plugin.php
  src/accordion.js
  src/blocks.js
  src/extend/accordion/attributes.js
  src/extend/accordion/components/AccordionTemplate.js
  src/extend/accordion/components/BlockAppender.js
  src/extend/accordion/components/ButtonInspectorControls.js
  src/extend/accordion/components/ContainerInspectorControls.js
  src/extend/accordion/edit.js
  src/extend/accordion/editor.scss
  src/extend/accordion/index.js
  src/utils/get-icon/index.js
Labels: refactoring

#782 Fix: No spaces in RichText using button tag name
  src/blocks/button/components/ButtonContentRenderer.js
Labels: bug

#780 Fix: Container mobile padding
  includes/blocks/class-container.php
Labels: bug

#786 Fix: Container error when uploading background image
  src/blocks/container/components/ComponentCSS.js
  src/blocks/container/css/main.js
Labels: bug

#788 Fix: Container appender positioning
  src/blocks/container/components/BlockAppender.js
Labels: bug

#789 Tweak: Use SpacingCSS for margins in editor
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/headline/css/main.js
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
  src/blocks/image/css/main.js
  src/blocks/image/css/mobile.js
  src/blocks/image/css/tablet.js
  src/extend/inspector-control/controls/spacing/components/SpacingCSS.js
Labels: refactoring

#791 Feature: Make sizing units consistent
  src/extend/inspector-control/controls/sizing/components/Height.js
  src/extend/inspector-control/controls/sizing/components/MaxHeight.js
  src/extend/inspector-control/controls/sizing/components/MaxWidth.js
  src/extend/inspector-control/controls/sizing/components/MinHeight.js
  src/extend/inspector-control/controls/sizing/components/MinWidth.js
  src/extend/inspector-control/controls/sizing/components/Width.js
  src/extend/inspector-control/controls/sizing/index.js
Labels: feature

#792 Feature: Add grid item width controls
  src/blocks/grid/components/WidthControls.js
  src/blocks/grid/edit.js
Labels: feature

#775 Improve advanced select results
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/query-parameters.js
  src/components/authors-select/index.js
  src/components/post-type-records-select/index.js
  src/components/taxonomies-select/index.js
  src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
Labels: feature

#794 Tweak: Use new editor_script/style handles
  includes/class-render-blocks.php
Labels: refactoring

#796 Tweak: Add current button colors
  src/blocks/button/css/main.js
Labels: feature
