Repository tomusborne/generateblocks, pull requests merged in 2022-12, with the labels that each got.

#798 Feature: Add position and overflow options
  includes/blocks/class-container.php
  includes/functions.php
  includes/general.php
  src/block-context/button.js
  src/block-context/container.js
  src/block-context/default.js
  src/block-context/headline.js
  src/blocks/container/css/main.js
  src/components/gradient/index.js
  src/components/migrate-inner-container/index.js
  src/components/migrate-inner-container/utils.js
  src/extend/inspector-control/controls/background-panel/components/background-options.js
  src/extend/inspector-control/controls/layout/attributes.js
  src/extend/inspector-control/controls/layout/components/FlexDirection.js
  src/extend/inspector-control/controls/layout/components/LayoutCSS.js
  src/extend/inspector-control/controls/layout/components/LayoutControl.js
  src/extend/inspector-control/controls/layout/index.js
  src/extend/inspector-control/controls/layout/options.js
  src/extend/inspector-control/controls/shapes-panel/index.js
Labels: feature

#797 Feature: Add onboard system
  includes/class-rest.php
  includes/general.php
  src/blocks/container/block-controls.js
  src/components/onboard-popover/index.js
  src/components/onboard-popover/onboards/insert-inner-container-onboard.js
  src/components/onboard-popover/styles.scss
Labels: feature

#799 Feature: Add more z-index options
  includes/general.php
  src/block-context/button.js
  src/block-context/headline.js
  src/extend/inspector-control/controls/layout/attributes.js
  src/extend/inspector-control/controls/layout/components/ZIndex.js
  src/extend/inspector-control/controls/layout/index.js
Labels: feature

#808 Tweak: Re-order panels
  src/extend/inspector-control/controls/layout/index.js
  src/extend/inspector-control/index.js
Labels: refactoring

#795 Feature: Add generateblocks.editor.renderBlock hook
  src/blocks/button/components/ButtonContentRenderer.js
  src/blocks/container/components/ContainerContentRenderer.js
  src/blocks/container/edit.js
  src/blocks/headline/components/HeadlineContentRenderer.js
  src/blocks/image/components/ImageContentRenderer.js
Labels: feature

#793 Feature: Add template selector system
  src/blocks/container/edit.js
  src/extend/template-selector/editor.scss
  src/extend/template-selector/index.js
  src/extend/template-selector/templateContext.js
Labels: feature

#806 Add Global Style warning in inner container migration modal
  src/blocks/container/editor.scss
  src/components/migrate-inner-container/index.js
Labels: refactoring

#810 Add generateblocks.editor.settingsPanel filter
  src/blocks/button-container/edit.js
  src/blocks/button/edit.js
  src/blocks/container/edit.js
  src/blocks/grid/components/WidthControls.js
  src/blocks/grid/edit.js
  src/blocks/headline/edit.js
  src/blocks/image/edit.js
Labels: refactoring

#807 Improve global max-width option
  includes/blocks/class-container.php
  includes/functions.php
  includes/general.php
  src/block-context/button.js
  src/block-context/headline.js
  src/blocks/container/attributes.js
  src/blocks/container/block-controls.js
  src/components/migrate-inner-container/utils.js
  src/components/unit-control/editor.scss
  src/components/unit-control/index.js
  src/dashboard.js
  src/extend/inspector-control/controls/sizing/attributes.js
  src/extend/inspector-control/controls/sizing/components/MaxWidth.js
  src/extend/inspector-control/controls/sizing/components/SizingCSS.js
  src/extend/inspector-control/controls/sizing/index.js
Labels: feature, bug

#811 Tweak: Don't set default button styles when using variant
  includes/defaults.php
  src/blocks/button/edit.js
Labels: refactoring

#812 Tweak: Ignore button hover colors on current buttons
  includes/blocks/class-button.php
  src/blocks/button/css/main.js
Labels: refactoring

#784 Feature: Add block selector filters
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-headline.php
  includes/functions.php
  includes/general.php
  src/blocks/button/css/main.js
Labels: feature

#814 Tweak: Improve Grid row-gap back-compat
  includes/blocks/class-grid.php
  src/blocks/grid/attributes.js
  src/blocks/grid/css/main.js
  src/blocks/grid/css/mobile.js
  src/blocks/grid/css/tablet.js
  src/components/number-control/index.js
  src/hoc/withGridLegacyMigration.js
Labels: refactoring

#817 Allow Template Selector to set attributes for parent
  src/extend/template-selector/index.js
Labels: feature

#819 Tweak: Add buttonType support for dynamic buttons
  includes/blocks/class-button.php
Labels: feature

#820 Feat: Add onboarding properties filter
  includes/general.php
Labels: feature

#821 Fix: Template selector missing inspector controls
  src/extend/template-selector/templateContext.js
Labels: bug

#822 Fix: Insert inner container button showing for variations
  src/blocks/container/block-controls.js
Labels: bug

#825 Tweak: Improve inner container migrate popover
  src/blocks/container/editor.scss
  src/components/migrate-inner-container/index.js
Labels: refactoring

#826 Tweak: Add more specificity to button link
  includes/general.php
Labels: refactoring

#830 Fix: Various migration bugs
  includes/blocks/class-container.php
  src/blocks/container/block-controls.js
  src/blocks/container/migrate-sizing.js
Labels: bug
