Repository tomusborne/generateblocks, pull requests merged in 2022-01, with the labels that each got.

#188 Add package-lock.json
  .gitignore
  package-lock.json
Labels: type: chore, priority: critical

#190 Moving bgOptions migration to migration hoc
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/edit.js
  src/hoc/withContainerLegacyMigration.js
Labels: type: bug, priority: low

#180 Add inline background image option
  .github/workflows/js-ci.yml
  .gitignore
  dist/blocks.asset.php
  dist/blocks.js
  includes/defaults.php
  includes/functions.php
  includes/general.php
  includes/generate-css.php
  package-lock.json
  package.json
  src/blocks/container/attributes.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/edit.js
  src/utils/get-background-image/index.js
Labels: type: feature, priority: critical

#192 Improve grid layout selector buttons
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/grid/components/LayoutSelector.js
  src/blocks/grid/editor.scss
Labels: type: feature, type: bug, priority: critical

#191 Add withDocumentation hoc
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button-container/components/InspectorControls.js
  src/blocks/button/components/InspectorControls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/grid/components/InspectorControls.js
  src/blocks/headline/components/InspectorControls.js
  src/hoc/index.js
  src/hoc/withDocumentation.js
Labels: type: feature

#193 Fix block margins in editor
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  src/blocks/button-container/css/main.js
  src/blocks/button-container/css/mobile.js
  src/blocks/button-container/css/tablet.js
  src/blocks/button-container/edit.js
  src/blocks/button/editor.scss
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/container/edit.js
  src/blocks/container/editor.scss
  src/blocks/grid/editor.scss
  src/blocks/headline/edit.js
  src/components/root-element/index.js
  src/shared/editor.scss
Labels: type: bug, priority: critical

#194 Add missing name props to InspectorControls
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/button-container/edit.js
  src/blocks/button/edit.js
  src/blocks/headline/edit.js
Labels: type: bug, priority: critical

#202 Update wp packages
  .eslintrc.json
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  package-lock.json
  package.json
  src/blocks/headline/components/dynamic-content/attributes.js
  src/blocks/headline/components/dynamic-content/components/SelectPostType.js
  src/blocks/headline/components/dynamic-content/hooks/useDynamicContent.js
  src/blocks/headline/components/dynamic-content/inspector-controls/DynamicSourceControl.js
  src/blocks/headline/components/dynamic-content/utils/getContent.js
  src/blocks/query-loop/attributes.js
  src/blocks/query-loop/components/InspectorControls.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/blocks/query-loop/components/inspector-controls/controls/DateTimePicker.js
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ParameterControl.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/index.js
  src/blocks/query-loop/hooks/useQueryLoopData.js
  src/blocks/query-loop/hooks/useQueryReducer.js
  src/blocks/query-loop/query-parameters.js
  src/components/advanced-select/index.js
  src/components/authors-select/index.js
  src/components/taxonomies-select/index.js
  src/utils/filter-attributes/index.js
  src/utils/object-is-empty.js
Labels: type: chore, priority: high
