Repository tomusborne/generateblocks, pull requests merged in 2022-06, with the labels that each got.

#523 Remove default width from blocks inside Containers
  dist/blocks.asset.php
  dist/blocks.css
  src/blocks/container/editor.scss
Labels: bug

#524 Fix: Posts select field error when post type does not support title
  dist/blocks.asset.php
  dist/blocks.js
  src/components/post-type-records-select/index.js
  src/extend/dynamic-content/components/SelectPost.js
  src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
Labels: bug

#527 Remove the class name option from Query Loops
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/query-loop/block.js
Labels: bug, query-loop

#528 Feature: Add option to define dynamic link type
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
Labels: feature, dynamic-content

#525 Change actions trigger from push to manual
  .github/workflows/assets.yml
Labels: chore

#537 Fix: Add alt and title fields to URL-only images
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
Labels: bug, image

#541 Fix: Per page limit in the editor
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/query-parameters.js
Labels: bug

#542 Fix: Background image opacity decimal places
  dist/blocks.asset.php
  dist/blocks.js
  src/blocks/container/components/InspectorControls.js
Labels: bug

#543 Fix: Block Elements width in GPP
  dist/blocks.asset.php
  dist/blocks.css
  src/shared/editor.scss
Labels: bug

#544 GitHub actions
  .github/workflows/build-package.yml
  .github/workflows/commit-dist-files.yml
  .github/workflows/js-ci.yml
Labels: chore

#545 Run commit dist files only on src/ files changes
  .github/workflows/build-package.yml
  .github/workflows/commit-dist-files.yml
  .github/workflows/js-ci.yml
  Gruntfile.js
  package.json
Labels: chore

#547 Fix package build with version
  .github/workflows/build-package.yml
  Gruntfile.js
Labels: chore

#546 Tweak: Only show image alt/title controls for Desktop
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
Labels: image

#550 Tweak: Improve editor per page cap
  src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/query-parameters.js
Labels: bug, query-loop

#551 Simplify grunt package
  Gruntfile.js
Labels: chore

#526 Release: 1.5.0-rc.1
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/class-dynamic-content.php
  package.json
  plugin.php
  readme.txt
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/editor.scss
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/blocks/query-loop/block.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/query-parameters.js
  src/components/post-type-records-select/index.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/components/SelectPost.js
  src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
  src/shared/editor.scss
Labels: chore

#554 Fix: Update Container type when dragged outside Grid
  src/blocks/container/components/InspectorControls.js
Labels: bug

#556 Fix: Remove non-working dynamic link types
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
Labels: bug

#558 Tweak: Change image description option value name
  includes/class-dynamic-content.php
  src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
  src/extend/dynamic-content/utils/getContent.js
Labels: image, refactoring

#565 Fix: Block error in editor mobile preview using fixed backgrounds
  src/blocks/container/css/mobile.js
Labels: bug, container

#566 Fix: Pagination block error
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
Labels: bug

#567 Feature: Add toggle to remove block if no dynamic link
  includes/class-render-blocks.php
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
Labels: feature, dynamic-content

#571 Fix: Inline Headline not inlining in the root
  src/blocks/headline/css/main.js
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
  src/components/root-element/index.js
Labels: bug, headline

#573 Add php ci
  .github/workflows/php-ci.yml
  composer.json
Labels: chore

#576 Tweak: Re-add :visited selectors
  includes/generate-css.php
  readme.txt
  src/blocks/container/css/main.js
Labels: refactoring

#577 Tweak: Increase Container link specificity in editor
  src/blocks/container/css/main.js
Labels: bug

#585 Quick fixes
  src/blocks/grid/block.js
  src/blocks/query-loop/components/utils.js
  src/components/taxonomies-select/index.js
Labels: chore

#587 Fix Actions
  .github/workflows/commit-dist-files.yml
  .github/workflows/js-ci.yml
  .github/workflows/php-ci.yml
Labels: chore

#588 Bump WP version to 5.9
  includes/class-render-blocks.php
  package.json
  plugin.php
  readme.txt
Labels: bug

#589 Release: 1.5.1
  includes/class-render-blocks.php
  package.json
  plugin.php
  readme.txt
Labels: release

#596 Fix: Container gridId attribute not updating correctly
  readme.txt
  src/blocks/container/components/InspectorControls.js
Labels: bug

#599 Fix: Button hasUrl attribute
  src/blocks/button/components/BlockControls.js
Labels: bug

#601 Fix: Sticky posts always displaying
  includes/class-query-loop.php
  package-lock.json
  readme.txt
  src/blocks/query-loop/components/inspector-controls/parameter-list/ParameterControl.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/query-parameters.js
Labels: feature

#605 Fix: Broken image block when avatars aren't available
  readme.txt
  src/blocks/image/components/ImagePlaceholder.js
  src/extend/dynamic-content/inspector-controls/ContentTypeControl.js
  src/extend/dynamic-content/utils/getContent.js
Labels: bug

#608 Tweak: Unset stickyPosts query arg
  includes/class-query-loop.php
Labels: bug

#610 Fix: Reset the query with wp_reset_postdata
  includes/class-render-blocks.php
Labels: bug

#611 Fix: Reset pagination numbers postdata
  includes/class-dynamic-content.php
Labels: bug
