Repository tomusborne/generateblocks, pull requests merged in 2022-07, with the labels that each got.

#614 Fix: Duplicated block toolbars when selecting links
  readme.txt
  src/blocks/query-loop/components/LoopRenderer.js
  src/blocks/query-loop/editor.scss
Labels: bug

#616 Fix: Dynamic placeholder border radius
  readme.txt
  src/blocks/image/css/main.js
  src/blocks/image/css/mobile.js
  src/blocks/image/css/tablet.js
  src/blocks/image/editor.scss
Labels: bug

#617 Fix: Inherit query feature
  includes/class-render-blocks.php
  readme.txt
Labels: bug

#620 Fix: Keep the order in which query loop parameter was included
  readme.txt
  src/blocks/query-loop/components/inspector-controls/parameter-list/index.js
Labels: bug

#623 Tweak: Move Post Template list view label to Container
  readme.txt
  src/blocks/container/block.js
  src/blocks/grid/block.js
Labels: bug

#612 Feature: Added filters to integrate related posts
  readme.txt
  src/blocks/query-loop/components/InspectorControls.js
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ParameterControl.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/query-parameters.js
  src/components/authors-select/index.js
  src/components/post-type-records-select/index.js
  src/components/taxonomies-select/index.js
Labels: feature

#621 Fix: Query loop taxonomy query include/exclude children
  includes/class-query-loop.php
  readme.txt
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/query-parameters.js
Labels: bug

#615 Release: 1.5.3
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/class-query-loop.php
  includes/class-render-blocks.php
  package-lock.json
  package.json
  plugin.php
  readme.txt
  src/blocks/container/block.js
  src/blocks/grid/block.js
  src/blocks/image/css/main.js
  src/blocks/image/css/mobile.js
  src/blocks/image/css/tablet.js
  src/blocks/image/editor.scss
  src/blocks/query-loop/components/InspectorControls.js
  src/blocks/query-loop/components/LoopRenderer.js
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ParameterControl.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/index.js
  src/blocks/query-loop/components/utils.js
  src/blocks/query-loop/editor.scss
  src/blocks/query-loop/query-parameters.js
  src/components/authors-select/index.js
  src/components/post-type-records-select/index.js
  src/components/taxonomies-select/index.js
Labels: release

#634 Fix: Non hierarchical taxonomies with broken REST API calls
  readme.txt
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/components/utils.js
Labels: bug

#633 Release: 1.5.4
  dist/blocks.asset.php
  dist/blocks.js
  package-lock.json
  package.json
  plugin.php
  readme.txt
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/components/utils.js
Labels: release
