Repository tomusborne/generateblocks, pull requests merged in 2022-02, with the labels that each got.

#203 Extract icon HTML in dynamic headline
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-render-blocks.php
  includes/functions.php
  src/blocks/headline/components/dynamic-content/attributes.js
Labels: type: bug, priority: critical

#206 Fix missing editor styles in Firefox
  includes/class-render-blocks.php
  readme.txt
Labels: type: bug, priority: high

#209 Fix query column heights
  dist/blocks.asset.php
  dist/blocks.css
  package-lock.json
  package.json
  src/blocks/grid/editor.scss
Labels: type: bug, priority: critical

#208 Query loop tweaks
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  dist/dashboard.asset.php
  src/blocks/button-container/components/ComponentCSS.js
  src/blocks/button/components/ComponentCSS.js
  src/blocks/container/components/ComponentCSS.js
  src/blocks/grid/components/ComponentCSS.js
  src/blocks/grid/editor.scss
  src/blocks/headline/components/BlockControls.js
  src/blocks/headline/components/ComponentCSS.js
  src/blocks/query-loop/components/QueryLoopRenderer.js
  src/blocks/query-loop/components/inspector-controls/SelectQueryParameter.js
  src/blocks/query-loop/components/query-loop-renderer/LoopRenderer.js
  src/blocks/query-loop/components/query-loop-renderer/index.js
  src/blocks/query-loop/components/query-loop-renderer/utils.js
  src/blocks/query-loop/hoc/withQueryLoop.js
Labels: type: feature, priority: high

#176 Add more dynamic headline options
  dist/blocks.asset.php
  dist/blocks.js
  includes/class-dynamic-content.php
  includes/class-render-blocks.php
  src/blocks/headline/block.js
  src/blocks/headline/components/dynamic-content/DynamicContentRenderer.js
  src/blocks/headline/components/dynamic-content/InspectorControls.js
  src/blocks/headline/components/dynamic-content/attributes.js
  src/blocks/headline/components/dynamic-content/hoc/withDynamicContent.js
  src/blocks/headline/components/dynamic-content/hooks/useDynamicContent.js
  src/blocks/headline/components/dynamic-content/hooks/usePostRecord.js
  src/blocks/headline/components/dynamic-content/inspector-controls/AuthorMetaControl.js
  src/blocks/headline/components/dynamic-content/inspector-controls/ContentTypeControl.js
  src/blocks/headline/components/dynamic-content/inspector-controls/LinkTypeControl.js
  src/blocks/headline/components/dynamic-content/inspector-controls/PostDateControl.js
  src/blocks/headline/components/dynamic-content/inspector-controls/PostMetaControl.js
  src/blocks/headline/components/dynamic-content/utils/applyContext.js
  src/blocks/headline/components/dynamic-content/utils/getContent.js
  src/blocks/query-loop/components/query-loop-renderer/index.js
Labels: type: feature, priority: critical

#216 Add dynamic content to GB buttons
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/class-render-blocks.php
  package-lock.json
  src/blocks/button/block.js
  src/blocks/button/components/BlockControls.js
  src/blocks/button/edit.js
  src/blocks/button/editor.scss
  src/blocks/headline/block.js
  src/blocks/headline/components/dynamic-content/DynamicContentRenderer.js
  src/blocks/headline/components/dynamic-content/InspectorControls.js
  src/blocks/headline/components/dynamic-content/attributes.js
  src/blocks/headline/edit.js
  src/utils/get-icon/index.js
Labels: type: feature, priority: critical

#223 Fix nested block post excerpts
  includes/general.php
Labels: type: bug, priority: medium

#229 Fix button not attributes changing
  dist/blocks.asset.php
  dist/blocks.js
  package-lock.json
  src/blocks/button/attributes.js
Labels: type: bug, priority: critical
