Repository tomusborne/generateblocks, pull requests merged in 2022-10, with the labels that each got.

#710 Refactor image block controls
  src/block-context/button-container.js
  src/block-context/button.js
  src/block-context/default.js
  src/block-context/headline.js
  src/block-context/image.js
  src/block-context/index.js
  src/blocks/image/components/InspectorControls.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/blocks/image/edit.js
  src/blocks/image/index.js
  src/components/dimensions/attributes.js
  src/extend/inspector-control/controls/settings-panel/index.js
  src/extend/inspector-control/index.js
  src/hoc/withResponsiveTabs.js
Labels: refactoring

#711 Grid block controls refactor
  src/block-context/grid.js
  src/block-context/index.js
  src/blocks/grid/block.js
  src/blocks/grid/components/InspectorControls.js
  src/blocks/grid/edit.js
  src/hoc/withResponsiveTabs.js
Labels: refactoring

#661 Release: 1.6.0
  dist/blocks.asset.php
  dist/blocks.js
  includes/blocks/class-button-container.php
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-grid.php
  includes/blocks/class-headline.php
  includes/blocks/class-image.php
  includes/blocks/class-query-loop.php
  includes/class-dynamic-content.php
  includes/class-enqueue-css.php
  includes/class-query-loop.php
  includes/class-render-blocks.php
  includes/defaults.php
  includes/functions.php
  includes/generate-css.php
  package-lock.json
  package.json
  plugin.php
  readme.txt
  src/blocks/button-container/edit.js
  src/blocks/container/components/ContainerContentRenderer.js
  src/blocks/container/edit.js
  src/blocks/headline/transforms.js
  src/blocks/image/components/ImageContentRenderer.js
  src/blocks/query-loop/components/LayoutSelector.js
  src/blocks/query-loop/components/inspector-controls/controls/DateTimePicker.js
  src/blocks/query-loop/components/inspector-controls/controls/TaxonomyParameterControl.js
  src/blocks/query-loop/components/inspector-controls/parameter-list/ControlBuilder.js
  src/components/LabelAndHelpWrapper/index.js
  src/components/advanced-select/index.js
  src/components/authors-select/index.js
  src/components/color-picker/index.js
  src/components/gradient/index.js
  src/components/icon-picker/index.js
  src/components/post-type-records-select/index.js
  src/components/root-element/index.js
  src/components/taxonomies-select/index.js
  src/extend/dynamic-content/DynamicRenderer.js
  src/extend/dynamic-content/InspectorControls.js
  src/extend/dynamic-content/attributes.js
  src/extend/dynamic-content/components/SelectPostType.js
  src/extend/dynamic-content/hooks/usePostRecord.js
  src/extend/dynamic-content/hooks/usePostTypeRecords.js
  src/extend/dynamic-content/inspector-controls/AuthorMetaControl.js
  src/extend/dynamic-content/inspector-controls/DynamicSourceControl.js
  src/extend/dynamic-content/inspector-controls/LinkTypeControl.js
  src/extend/dynamic-content/inspector-controls/PostMetaControl.js
  src/extend/dynamic-content/utils/getContent.js
  src/extend/dynamic-content/utils/getContentTypeLabel.js
  src/hooks/useAuthors.js
  src/hooks/useRecordsReducer.js
  src/hooks/useTaxonomyRecords.js
Labels: release

#714 Refactor Container block inspector controls
  src/block-context/container.js
  src/block-context/default.js
  src/block-context/index.js
  src/blocks/container/block.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/edit.js
  src/extend/inspector-control/controls/background-panel/components/attachment.js
  src/extend/inspector-control/controls/background-panel/components/background-color-overlay.js
  src/extend/inspector-control/controls/background-panel/components/background-options.js
  src/extend/inspector-control/controls/background-panel/components/image-opacity.js
  src/extend/inspector-control/controls/background-panel/components/image-size.js
  src/extend/inspector-control/controls/background-panel/components/image-url.js
  src/extend/inspector-control/controls/background-panel/components/position.js
  src/extend/inspector-control/controls/background-panel/components/repeat.js
  src/extend/inspector-control/controls/background-panel/components/selector.js
  src/extend/inspector-control/controls/background-panel/components/size.js
  src/extend/inspector-control/controls/background-panel/components/use-inline-style.js
  src/extend/inspector-control/controls/background-panel/index.js
  src/extend/inspector-control/controls/colors/index.js
  src/extend/inspector-control/controls/shapes-panel/index.js
  src/extend/inspector-control/controls/spacing/components/minimum-height.js
  src/extend/inspector-control/controls/spacing/components/vertical-alignment.js
  src/extend/inspector-control/controls/spacing/components/z-index.js
  src/extend/inspector-control/controls/spacing/index.js
  src/extend/inspector-control/controls/spacing/options.js
  src/extend/inspector-control/index.js
  src/hoc/withResponsiveTabs.js
Labels: refactoring

#718 Feature: Remove the "Remove Vertical Gap" option
  includes/blocks/class-grid.php
  src/blocks/container/components/InspectorControls.js
  src/blocks/grid/css/main.js
  src/blocks/grid/css/mobile.js
  src/blocks/grid/css/tablet.js
  src/blocks/query-loop/components/BlockControls.js
  src/hoc/withGridLegacyMigration.js
Labels: feature

#719 Tweak: Remove ...props from UnitControl
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/components/unit-control/index.js
Labels: refactoring

#720 Tweak: Move tagName option to Advanced
  src/blocks/container/components/InspectorAdvancedControls.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/components/TagName.js
  src/blocks/container/edit.js
Labels: refactoring

#721 Feature: New Sizing controls
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/functions.php
  includes/general.php
  src/block-context/button.js
  src/block-context/container.js
  src/block-context/default.js
  src/block-context/index.js
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/button/editor.scss
  src/blocks/container/attributes.js
  src/blocks/container/components/InspectorControls.js
  src/blocks/container/components/LayoutControls.js
  src/blocks/container/components/LegacyLayoutControls.js
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/container/edit.js
  src/blocks/container/editor.scss
  src/blocks/container/migrate-sizing.js
  src/blocks/image/components/inspector-controls/ImageSettingsControl.js
  src/components/unit-control/editor.scss
  src/components/unit-control/index.js
  src/components/unit-picker/editor.scss
  src/components/unit-picker/index.js
  src/extend/inspector-control/controls/sizing/attributes.js
  src/extend/inspector-control/controls/sizing/components/Height.js
  src/extend/inspector-control/controls/sizing/components/MaxHeight.js
  src/extend/inspector-control/controls/sizing/components/MaxWidth.js
  src/extend/inspector-control/controls/sizing/components/MinHeight.js
  src/extend/inspector-control/controls/sizing/components/MinWidth.js
  src/extend/inspector-control/controls/sizing/components/SizingCSS.js
  src/extend/inspector-control/controls/sizing/components/Width.js
  src/extend/inspector-control/controls/sizing/editor.scss
  src/extend/inspector-control/controls/sizing/index.js
  src/extend/inspector-control/controls/spacing/components/minimum-height.js
  src/extend/inspector-control/controls/spacing/components/vertical-alignment.js
  src/extend/inspector-control/controls/spacing/index.js
  src/extend/inspector-control/controls/spacing/options.js
  src/extend/inspector-control/index.js
  src/hoc/withContainerLegacyMigration.js
  src/utils/add-to-css/index.js
  src/utils/get-icon/index.js
  src/utils/sizingValue/index.js
Labels: feature

#717 Feature: Add Layout controls to Headline block
  includes/blocks/class-headline.php
  src/block-context/headline.js
  src/blocks/headline/attributes.js
  src/blocks/headline/css/main.js
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
  src/blocks/headline/edit.js
  src/components/icon-picker/index.js
  src/extend/inspector-control/controls/icon/index.js
  src/hoc/withHeadlineLegacyMigration.js
Labels: feature

#725 Remove headline alignment options when using flex
  src/blocks/headline/components/BlockControls.js
  src/blocks/headline/edit.js
Labels: bug

#727 Feature: Add flex child controls to Headline and Button blocks
  includes/blocks/class-button.php
  includes/blocks/class-headline.php
  src/block-context/button.js
  src/block-context/headline.js
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/headline/css/main.js
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
Labels: feature

#726 Move migrate inner container to layout panel
  src/block-context/index.js
  src/blocks/container/components/InspectorAdvancedControls.js
  src/blocks/container/components/MigrateInnerContainer.js
  src/extend/inspector-control/controls/layout/index.js
Labels: refactoring

#729 Feature: Add gap options to our blocks
  includes/functions.php
  includes/general.php
  src/block-context/button.js
  src/block-context/container.js
  src/block-context/default.js
  src/block-context/headline.js
  src/extend/inspector-control/controls/layout/attributes.js
  src/extend/inspector-control/controls/layout/components/LayoutCSS.js
  src/extend/inspector-control/controls/layout/components/editor.scss
  src/extend/inspector-control/controls/layout/index.js
Labels: feature

#730 Feature: Add Button Container variation
  src/blocks/button-container/block.js
  src/blocks/button/components/BlockControls.js
  src/blocks/container/block.js
  src/blocks/container/variations/button-container/BlockAppender.js
  src/blocks/container/variations/button-container/InspectorControls.js
  src/blocks/container/variations/button-container/index.js
  src/blocks/container/variations/index.js
  src/blocks/container/variations/section/index.js
  src/blocks/query-loop/components/BlockControls.js
  src/extend/inspector-control/controls/layout/components/FlexDirection.js
  src/extend/inspector-control/controls/layout/components/LayoutControl.js
  src/utils/get-icon/index.js
Labels: feature

#731 Tweak: Improve inner container migration logic
  src/blocks/container/components/MigrateInnerContainer.js
Labels: bug

#736 Tweak: Improve Container block appender
  src/blocks/container/css/main.js
  src/blocks/container/editor.scss
Labels: feature

#738 Feature: Move Button Container option to toolbar
  src/blocks/button/components/BlockControls.js
  src/blocks/container/variations/button-container/index.js
Labels: feature

#740 Tweak: Change panel icon color
  src/shared/editor.scss
Labels: refactoring

#744 Tweak: Update block icons
  assets/css/dashboard.css
  includes/dashboard.php
  src/blocks/container/editor.scss
  src/shared/editor.scss
  src/utils/get-icon/index.js
Labels: feature

#747 Fix: Excerpt spelling mistake
  src/extend/dynamic-content/utils/getContent.js
Labels: bug

#735 Improve inner container migration
  src/blocks/container/components/MigrateInnerContainer.js
  src/components/migrate-inner-container/index.js
  src/components/migrate-inner-container/utils.js
  src/extend/inspector-control/controls/layout/index.js
Labels: feature

#745 Tweak: Simplify button layout when inserted
  includes/defaults.php
  src/blocks/button/edit.js
Labels: refactoring

#746 Tweak: Improve logic of UnitControl split
  src/components/unit-control/index.js
Labels: feature

#748 Fix: Nested block appenders
  src/blocks/container/css/main.js
Labels: bug
