Repository tomusborne/generateblocks, pull requests merged in 2023-06, with the labels that each got.

#1028 Tweak: Keep Container text align option when using flex
  src/blocks/container/components/BlockControls.js
Labels: feature

#1030 Tweak: Clean up `UnitControl` display
  src/components/dimensions/editor.scss
  src/components/unit-control/editor.scss
  src/extend/inspector-control/controls/sizing/index.js
  src/utils/get-icon/index.js
Labels: bug

#1031 Tweak: Clean up un-used components
  Gruntfile.js
  src/components/dimensions-group/index.js
  src/components/typography/editor.scss
  src/components/typography/index.js
  src/extend/inspector-control/controls/typography/components/font-family.js
  src/extend/inspector-control/controls/typography/google-fonts.json
Labels: refactoring

#1025 Feature: Only show one dimension field if synced
  src/components/dimensions/index.js
Labels: feature

#1033 Fix: Flex icons based on direction in device previews
  src/extend/inspector-control/controls/layout/index.js
Labels: bug

#1034 Fix: Container appender icon spacing
  src/blocks/container/editor.scss
Labels: bug

#1037 Fix: useDeviceType state was one state behind when triggered from core buttons
  src/hooks/useDeviceType.js
Labels: bug

#1026 Feature: Sync all border values on sync click
  src/components/color-picker/index.js
  src/extend/inspector-control/controls/borders/index.js
Labels: feature

#1041 Clean up deprecated code
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-headline.php
  src/blocks/button/css/main.js
  src/blocks/container/css/main.js
  src/blocks/headline/css/main.js
Labels: feature

#1042 Fix: Use unit in `UnitControl` if value starts with decimal
  readme.txt
  src/components/unit-control/index.js
Labels: bug

#1044 Fix: Query Loop templateLock issue
  src/blocks/container/components/ContainerContentRenderer.js
Labels: bug

#1046 Fix: Broken device buttons when sync preview turned off
  src/hooks/useDeviceType.js
Labels: bug

#1045 Fix: Attributes merging incorrect values when multiple blocks are selected
  readme.txt
  src/blocks/button/components/BlockControls.js
  src/blocks/button/edit.js
  src/blocks/container/components/BlockControls.js
  src/blocks/container/edit.js
  src/blocks/grid/components/WidthControls.js
  src/blocks/headline/components/BlockControls.js
  src/blocks/headline/edit.js
  src/blocks/image/edit.js
  src/components/icon-picker/index.js
  src/extend/inspector-control/controls/background-panel/components/background-options.js
  src/extend/inspector-control/controls/background-panel/index.js
  src/extend/inspector-control/controls/borders/index.js
  src/extend/inspector-control/controls/icon/index.js
  src/extend/inspector-control/controls/sizing/index.js
  src/extend/inspector-control/controls/typography/components/font-family.js
  src/extend/inspector-control/controls/typography/index.js
  src/hoc/withSetAttributes.js
  src/hooks/useDeviceAttributes.js
  src/tests/unit/deepMergeAttributes.test.js
Labels: bug

#1047 Tweak: Integrate new spacing with layout migration
  src/components/migrate-inner-container/utils.js
Labels: bug

#1053 Fix: Allow negative value number in `UnitControl`
  src/components/unit-control/index.js
Labels: bug

#1057 Tweak: Clean up `UnitControl`
  src/components/unit-control/index.js
Labels: refactoring

#1063 Tweak: Force lowercase units in `UnitControl`
  src/components/unit-control/index.js
Labels: bug

#1068 Tweak: Remove top/bottom margin from Query Loop in the editor
  readme.txt
  src/blocks/query-loop/editor.scss
Labels: bug

#1066 Tweak: Remove `isSmall` from sync buttons
  src/components/dimensions/index.js
  src/extend/inspector-control/controls/borders/index.js
Labels: bug

#1067 Fix: Logical tabbing order of `Dimensions` component
  src/components/dimensions/editor.scss
  src/components/dimensions/index.js
  src/components/dimensions/labels.js
  src/extend/inspector-control/controls/borders/index.js
  src/extend/inspector-control/controls/spacing/index.js
Labels: feature
