Repository tomusborne/generateblocks, pull requests merged in 2023-08, with the labels that each got.

#1101 Fix/border color not showing
  readme.txt
  src/extend/inspector-control/controls/borders/index.js
Labels: bug

#1099 Tweak: Add support for the newly created core function "wp_img_tag_add_loading_optimization_attrs"
  includes/functions.php
  readme.txt
Labels: chore

#1113 Tweak: Load block margin/max-width resets before block CSS
  includes/general.php
  src/extend/inspector-control/controls/sizing/components/SizingCSS.js
  src/extend/inspector-control/controls/spacing/components/SpacingCSS.js
Labels: refactoring
