Repository tomusborne/generateblocks, pull requests merged in 2023-05, with the labels that each got.

#986 Tweak: Align buttons in a row using alignment matrix
  src/extend/block-controls/controls/alignment-matrix-control.js
  src/utils/get-unique-block-names/index.js
Labels: feature

#987 Tweak: Remove the Button Container variation
  src/blocks/container/block.js
  src/blocks/container/variations/button-container/BlockAppender.js
  src/blocks/container/variations/button-container/index.js
  src/blocks/container/variations/index.js
  src/extend/block-controls/toolbar-appenders/index.js
Labels: feature

#992 Feature: Migrate typography & add more unit control
  includes/blocks/class-button.php
  includes/blocks/class-container.php
  includes/blocks/class-headline.php
  includes/functions.php
  src/blocks/button/components/BlockControls.js
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/button/edit.js
  src/blocks/container/components/BlockControls.js
  src/blocks/container/css/main.js
  src/blocks/container/css/mobile.js
  src/blocks/container/css/tablet.js
  src/blocks/container/edit.js
  src/blocks/headline/components/BlockControls.js
  src/blocks/headline/css/main.js
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
  src/blocks/headline/edit.js
  src/components/google-font-link/index.js
  src/components/unit-control/index.js
  src/extend/inspector-control/controls/typography/attributes.js
  src/extend/inspector-control/controls/typography/components/TypographyCSS.js
  src/extend/inspector-control/controls/typography/components/font-family.js
  src/extend/inspector-control/controls/typography/components/font-size.js
  src/extend/inspector-control/controls/typography/components/letter-spacing.js
  src/extend/inspector-control/controls/typography/components/line-height.js
  src/extend/inspector-control/controls/typography/index.js
  src/hoc/migrations/migrateTypography.js
  src/hoc/withButtonLegacyMigration.js
  src/hoc/withContainerLegacyMigration.js
  src/hoc/withHeadlineLegacyMigration.js
  src/tests/unit/migrateTypography.test.js
  src/utils/get-responsive-placeholder/index.js
Labels: feature

#993 Tweak: Improve icon sizing control
  includes/blocks/class-button.php
  includes/blocks/class-headline.php
  includes/functions.php
  src/block-context/button.js
  src/block-context/default.js
  src/block-context/headline.js
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/headline/css/main.js
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
  src/components/icon-picker/editor.scss
  src/extend/inspector-control/controls/icon/attributes.js
  src/extend/inspector-control/controls/icon/components/icon-size.js
  src/extend/inspector-control/controls/icon/index.js
  src/hoc/migrations/migratingIconSizing.js
  src/hoc/withButtonLegacyMigration.js
  src/hoc/withHeadlineLegacyMigration.js
  src/tests/unit/migrateIconSizing.test.js
Labels: feature

#995 Feature: Add block labels to the list view
  src/blocks/button/block.js
  src/blocks/container/attributes.js
  src/blocks/container/block.js
  src/blocks/container/components/InspectorAdvancedControls.js
  src/blocks/image/index.js
Labels: feature

#991 Fix: Query loop parameter delete button size
  src/blocks/query-loop/editor.scss
Labels: bug

#999 Fix: Matrix alignment not working for inline-flex
  src/extend/block-controls/controls/alignment-matrix-control.js
Labels: bug

#1000 Fix: Advanced select jumping when near the bottom of the page
  package-lock.json
  package.json
  src/components/advanced-select/index.js
Labels: bug

#1004 Tweak: Use "Icon" as list view label
  src/blocks/button/block.js
  src/blocks/headline/block.js
Labels: feature

#1006 Fix: Allow objects in useDeviceAttributes
  src/extend/inspector-control/controls/icon/components/icon-padding.js
  src/hooks/useDeviceAttributes.js
Labels: bug

#1003 Fix: Device attributes to work with nested objects
  src/extend/inspector-control/controls/icon/components/icon-padding.js
  src/hooks/test/useDeviceAttributesTest.js
  src/hooks/useDeviceAttributes.js
  src/tests/unit/useDeviceAttributes.test.js
Labels: bug

#996 Tweak: Migrate icon padding
  includes/blocks/class-button.php
  includes/blocks/class-headline.php
  includes/class-legacy-attributes.php
  includes/general.php
  src/blocks/button/css/main.js
  src/blocks/button/css/mobile.js
  src/blocks/button/css/tablet.js
  src/blocks/headline/css/main.js
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
  src/components/dimensions/index.js
  src/extend/inspector-control/controls/icon/components/icon-padding.js
  src/hoc/migrations/migrateDimensions.js
  src/hoc/migrations/migrateIconPadding.js
  src/hoc/migrations/migrateTypography.js
  src/hoc/migrations/migratingIconSizing.js
  src/hoc/migrations/utils.js
  src/hoc/withButtonLegacyMigration.js
  src/hoc/withHeadlineLegacyMigration.js
  src/hooks/test/useDeviceAttributesTest.js
  src/hooks/useDeviceAttributes.js
  src/tests/unit/blockVersion.test.js
  src/tests/unit/migrateDimensions.test.js
  src/tests/unit/migrateHeadlineFlex.test.js
  src/tests/unit/migrateIconSizing.test.js
  src/tests/unit/migrateTypography.test.js
  src/tests/unit/useDeviceAttributes.test.js
  tests/Unit/LegacyAttributesTest.php
Labels: feature

#1001 Tweak: Add better migration system to all blocks
  src/blocks/container/migrate-sizing.js
  src/hoc/migrations/migrateDimensions.js
  src/hoc/migrations/migrateIconPadding.js
  src/hoc/migrations/migrateSizing.js
  src/hoc/migrations/migrateTypography.js
  src/hoc/migrations/migratingIconSizing.js
  src/hoc/migrations/utils.js
  src/hoc/withButtonContainerLegacyMigration.js
  src/hoc/withButtonLegacyMigration.js
  src/hoc/withContainerLegacyMigration.js
  src/hoc/withGridLegacyMigration.js
  src/hoc/withHeadlineLegacyMigration.js
  src/hoc/withImageLegacyMigration.js
  src/tests/unit/addToAttrsObject.test.js
  src/tests/unit/migrations/migrateButtonLayout.test.js
  src/tests/unit/migrations/migrateContainerZIndex.test.js
  src/tests/unit/migrations/migrateDimensions.test.js
  src/tests/unit/migrations/migrateFlexBasis.test.js
  src/tests/unit/migrations/migrateHeadlineFlex.test.js
  src/tests/unit/migrations/migrateIconSizing.test.js
  src/tests/unit/migrations/migrateInnerContainer.test.js
  src/tests/unit/migrations/migrateOldButtonDefaults.test.js
  src/tests/unit/migrations/migrateOldContainerDefaults.test.js
  src/tests/unit/migrations/migrateOldGridDefaults.test.js
  src/tests/unit/migrations/migrateSizing.test.js
  src/tests/unit/migrations/migrateStackFill.test.js
  src/tests/unit/migrations/migrateTypography.test.js
  src/tests/unit/migrations/withButtonContainerMigration.test.js
Labels: refactoring

#1008 Tweak: Map old typography attributes
  includes/blocks/class-button.php
  includes/blocks/class-headline.php
  includes/class-map-deprecated-attributes.php
  includes/functions.php
  tests/Unit/MapDeprecatedAttributesTest.php
  tests/unit/DynamicCSSTest.php
Labels: refactoring

#1013 Fix: Triple captions using static image with dynamic link
  includes/class-dynamic-content.php
Labels: bug

#1016 Tweak: Set Colors panel initialOpen to false
  .github/workflows/ci.yml
  src/extend/inspector-control/controls/colors/index.js
Labels: refactoring

#1010 Feature: Add option to disable Google fonts
  includes/class-rest.php
  includes/defaults.php
  includes/functions.php
  includes/general.php
  src/components/google-font-link/index.js
  src/dashboard.js
  src/extend/inspector-control/controls/typography/components/font-family.js
  src/extend/inspector-control/controls/typography/options.js
Labels: feature

#1021 Chore: Add more migration tests
  includes/functions.php
  src/components/icon-picker/index.js
  src/hoc/migrations/migrateBorders.js
  src/hoc/migrations/migrateIconPadding.js
  src/hoc/migrations/migrateSizing.js
  src/hoc/migrations/migrateSpacing.js
  src/hoc/migrations/migrateTypography.js
  src/hoc/migrations/migratingIconSizing.js
  src/hoc/withButtonContainerLegacyMigration.js
  src/hoc/withButtonLegacyMigration.js
  src/hoc/withContainerLegacyMigration.js
  src/hoc/withGridLegacyMigration.js
  src/hoc/withHeadlineLegacyMigration.js
  src/hoc/withImageLegacyMigration.js
  src/tests/unit/migrations/defaults.js
  src/tests/unit/migrations/migrateBorders.test.js
  src/tests/unit/migrations/migrateIconSizing.test.js
  src/tests/unit/migrations/migrateSpacing.test.js
  src/tests/unit/migrations/migrateTypography.test.js
  src/tests/unit/migrations/withButtonContainerMigration.test.js
  src/tests/unit/migrations/withButtonMigration.test.js
  src/tests/unit/migrations/withContainerMigration.test.js
  src/tests/unit/migrations/withGridMigration.test.js
  src/tests/unit/migrations/withHeadlineMigration.test.js
  src/tests/unit/migrations/withImageMigration.test.js
  tests/unit/DynamicCSSTest.php
Labels: chore
