Repository tomusborne/generateblocks, pull requests merged in 2023-01, with the labels that each got.

#835 Fix: Improve device type check in the editor
  src/blocks/button-container/edit.js
  src/blocks/button/components/BlockControls.js
  src/blocks/button/edit.js
  src/blocks/container/components/BlockControls.js
  src/blocks/container/components/TagName.js
  src/blocks/container/edit.js
  src/blocks/grid/components/WidthControls.js
  src/blocks/grid/edit.js
  src/blocks/headline/components/BlockControls.js
  src/blocks/headline/components/TagName.js
  src/blocks/headline/edit.js
  src/blocks/image/edit.js
  src/components/unit-control/index.js
  src/extend/inspector-control/controls/flex-child-panel/components/FlexControls.js
  src/extend/inspector-control/controls/flex-child-panel/index.js
  src/extend/inspector-control/controls/icon/components/icon-padding.js
  src/extend/inspector-control/controls/icon/components/icon-size.js
  src/extend/inspector-control/controls/icon/index.js
  src/extend/inspector-control/controls/layout/index.js
  src/extend/inspector-control/controls/shapes-panel/index.js
  src/extend/inspector-control/controls/sizing/index.js
  src/extend/inspector-control/controls/spacing/index.js
  src/extend/inspector-control/controls/typography/index.js
  src/extend/inspector-control/index.js
  src/utils/get-device-type/index.js
Labels: bug

#838 Fix: Dynamic button tag name
  includes/blocks/class-button.php
  readme.txt
Labels: bug

#837 Tweak: Make pagination button selectors more specific
  includes/class-query-loop.php
  includes/general.php
  src/blocks/query-loop/components/BlockControls.js
Labels: bug

#839 Fix: Pagination button query filters
  includes/class-dynamic-content.php
  readme.txt
Labels: bug

#840 Fix: Device switching
  src/block-context/index.js
  src/blocks/button-container/edit.js
  src/blocks/button/edit.js
  src/blocks/container/edit.js
  src/blocks/grid/edit.js
  src/blocks/headline/edit.js
  src/blocks/image/edit.js
  src/hoc/index.js
  src/hoc/withDeviceType.js
  src/hooks/useDeviceType.js
  src/utils/get-device-type/index.js
Labels: bug

#841 Fix: Query Loop template widths
  src/blocks/query-loop/templates.js
Labels: bug

#842 Tweak: Improve Button selector specificity
  includes/general.php
Labels: bug

#844 Fix: Pass $block to parse_attr function
  includes/functions.php
Labels: bug

#846 Fix: Block max-width
  src/blocks/image/css/main.js
  src/extend/inspector-control/controls/sizing/components/SizingCSS.js
Labels: bug

#849 Tweak: Force lowercase margin value
  src/components/dimensions/editor.scss
  src/components/dimensions/index.js
Labels: refactoring

#848 Tweak: Allow 0 as HTML attribute
  includes/functions.php
  readme.txt
Labels: feature

#851 Tweak: Load CSS later
  includes/class-enqueue-css.php
  readme.txt
Labels: refactoring

#853 Tweak: Move migrateSizing into version check
  src/hoc/withContainerLegacyMigration.js
Labels: refactoring

#854 Tweak: Prevent faded background image in editor
  src/blocks/container/components/ContainerContentRenderer.js
Labels: bug

#856 Fix: min-width not working in editor
  src/extend/inspector-control/controls/sizing/components/SizingCSS.js
Labels: bug

#857 Tweak: Replace gb-button__current class with gb-block-is-current
  includes/blocks/class-button.php
  includes/class-dynamic-content.php
  readme.txt
Labels: refactoring

#858 Fix: Button defaults
  includes/blocks/class-button.php
Labels: bug

#860 Tweak: Don't apply sizing to inner Container
  src/components/migrate-inner-container/utils.js
Labels: bug

#861 Tweak: Re-order panels
  src/extend/inspector-control/index.js
Labels: refactoring

#870 Fix: Re-usable content removed during Container migration
  src/components/migrate-inner-container/index.js
  src/components/migrate-inner-container/utils.js
Labels: bug

#868 Fix: Grid columns dont have width set correctly
  src/blocks/grid/components/LayoutSelector.js
Labels: bug

#867 Fix: Add pointer-events to pseudo background
  includes/blocks/class-container.php
  readme.txt
  src/blocks/container/css/main.js
Labels: bug

#871 Feat: Add EM to column/row gaps
  src/extend/inspector-control/controls/layout/index.js
Labels: feature

#873 Update github actions
  .github/workflows/build-package.yml
  .github/workflows/commit-dist-files.yml
  .github/workflows/cy.yml
  .github/workflows/js-ci.yml
  .github/workflows/php-ci.yml
Labels: chore

#877 Tweak: Add tag name selectors to Headlines and Buttons
  includes/general.php
Labels: refactoring

#884 Fix: Add deep path for file changes check
  .github/workflows/ci.yml
Labels: chore

#883 Fix: Headline device spacing in editor
  src/blocks/headline/css/mobile.js
  src/blocks/headline/css/tablet.js
Labels: bug

#882 Tweak: Show inherited highlight in layout buttons
  src/extend/inspector-control/controls/layout/components/FlexDirection.js
  src/extend/inspector-control/controls/layout/components/LayoutControl.js
  src/extend/inspector-control/controls/layout/index.js
  src/shared/editor.scss
Labels: feature

#892 Fix: Missing device buttons when using multi-select
  src/extend/inspector-control/controls/responsive-tabs/index.js
Labels: bug

#894 Fix: Show device-specific shape panel options
  src/extend/inspector-control/controls/shapes-panel/index.js
  src/extend/inspector-control/index.js
Labels: bug

#895 Fix: Triple captions using static image with dynamic link
  includes/class-dynamic-content.php
  readme.txt
Labels: bug

#900 Revert: Triple captions using static image with dynamic link
  includes/class-dynamic-content.php
  readme.txt
Labels: bug
