Repository tomusborne/generateblocks, pull requests merged in 2023-04, with the labels that each got.

#960 Fix: Button with dynamic content not displaying the aria-label
  includes/blocks/class-button.php
Labels: bug

#959 Fix: Template lock system not applying to inner blocks
  src/blocks/container/attributes.js
  src/blocks/container/components/ContainerContentRenderer.js
  src/blocks/grid/attributes.js
  src/blocks/grid/edit.js
Labels: bug

#966 Fix: React createRoot warning
  package-lock.json
  package.json
  src/extend/inspector-control/controls/responsive-tabs/index.js
  src/utils/compatible-render/index.js
Labels: refactoring

#955 Fix: Color and Background panels are visible/accessible on Responsive views
  src/extend/inspector-control/index.js
Labels: bug

#962 Feature: Add block appender toolbar
  src/blocks.js
  src/blocks/button/components/BlockControls.js
  src/blocks/container/block-controls.js
  src/blocks/container/block.js
  src/blocks/container/transforms.js
  src/blocks/container/variations/button-container/InspectorControls.js
  src/blocks/container/variations/button-container/index.js
  src/extend/block-controls/index.js
  src/extend/block-controls/toolbar-appenders/index.js
  src/utils/get-icon/index.js
  src/utils/get-unique-block-names/index.js
Labels: feature

#974 Feature: Move block alignment to Layout panel
  src/block-context/container.js
  src/block-context/default.js
  src/blocks/container/block-controls.js
  src/extend/inspector-control/controls/layout/components/ThemeWidth.js
  src/extend/inspector-control/controls/layout/index.js
Labels: feature

#954 Chore: Add PHP tests
  .distignore
  .github/workflows/ci.yml
  .gitignore
  composer.json
  phpcs.xml.dist
  phpunit.xml
  tests/bootstrap.php
  tests/unit/DynamicCSSTest.php
Labels: chore

#979 Fix: Double-click when selecting Grid template
  src/blocks/grid/components/InspectorControls.js
  src/blocks/grid/edit.js
Labels: bug

#978 Feature: Add alignment matrix component
  src/blocks/container/components/BlockControls.js
  src/components/alignment-matrix/components/cell.js
  src/components/alignment-matrix/components/matrix.js
  src/components/alignment-matrix/index.js
  src/components/alignment-matrix/styles.scss
  src/extend/block-controls/controls/alignment-matrix-control.js
  src/extend/block-controls/controls/templates.js
  src/hooks/test/useDeviceAttributesTest.js
  src/hooks/useDeviceAttributes.js
  src/utils/get-icon/index.js
Labels: feature
