Repository tomusborne/generateblocks, pull requests merged in 2023-03, with the labels that each got.

#919 Fix: Migrate Container sizing for old blocks
  readme.txt
  src/hoc/withContainerLegacyMigration.js
Labels: bug

#926 Tweak: Add link to documentation under legacy layout toggle
  readme.txt
  src/components/migrate-inner-container/index.js
Labels: refactoring

#928 Tweak: Use function to add global defaults instead of filter
  includes/defaults.php
  includes/functions.php
  includes/general.php
Labels: bug

#929 Fix: Missing block styling with some third-party plugins
  includes/class-enqueue-css.php
  includes/functions.php
  readme.txt
Labels: bug

#930 Fix: Onboard popover width
  src/components/onboard-popover/styles.scss
Labels: refactoring

#920 Release: 1.7.1
  dist/blocks.asset.php
  dist/blocks.css
  dist/blocks.js
  includes/class-enqueue-css.php
  includes/defaults.php
  includes/functions.php
  includes/general.php
  package.json
  plugin.php
  readme.txt
  src/components/migrate-inner-container/index.js
  src/components/onboard-popover/styles.scss
  src/hoc/withContainerLegacyMigration.js
Labels: release

#931 Fix: Onboarding keys registered by GBP weren't optional
  includes/general.php
Labels: bug

#932 Fix: Block styling in block theme templates
  includes/class-enqueue-css.php
Labels: bug

#933 Release: 1.7.2
  includes/class-enqueue-css.php
  includes/general.php
  package.json
  plugin.php
  readme.txt
Labels: release

#936 Fix: REST API warnings
  includes/general.php
Labels: bug

#934 Release: 1.7.3
  dist/blocks.asset.php
  dist/blocks.js
  includes/general.php
  package.json
  plugin.php
  readme.txt
  src/blocks/button-container/deprecated.js
  src/blocks/button/deprecated.js
  src/blocks/container/deprecated.js
  src/blocks/grid/deprecated.js
  src/blocks/headline/deprecated.js
Labels: release
