Repository tomusborne/generateblocks, pull requests merged in 2024-12, with the labels that each got.

#1555 Update styles-builder
  package-lock.json
  package.json
Labels: bug

#1545 Feature: Add shape divider position options
  src/blocks/shape/components/BlockSettings.jsx
  src/blocks/shape/components/ShapeDividerControls.jsx
Labels: feature

#1556 Tweak: Make styles builder filter persist
  package-lock.json
  package.json
Labels: feature

#1557 Fix: Shape location shortcuts always showing
  src/blocks/shape/components/ShapeDividerControls.jsx
Labels: bug

#1558 Fix: React update error
  src/blocks/loop-item/edit.js
Labels: bug

#1568 Tweak: Loop item fixes
  src/blocks/loop-item/edit.js
  src/blocks/looper/block.json
Labels: bug

#1569 Feature: Add `media` dynamic tag
  includes/dynamic-tags/class-dynamic-tag-callbacks.php
  includes/dynamic-tags/class-dynamic-tags.php
  src/dynamic-tags/components/DynamicTagSelect.jsx
Labels: feature

#1576 Fix: Taxonomy term dynamic tags
  includes/dynamic-tags/class-dynamic-tags.php
Labels: bug

#1571 Feature: Add alignment toolbar
  src/blocks/element/block.json
  src/blocks/element/edit.js
  src/blocks/media/block.json
  src/blocks/media/edit.js
  src/blocks/media/editor.scss
  src/blocks/text/edit.js
  src/components/alignment-toolbar/AlignmentToolbar.jsx
  src/components/alignment-toolbar/BlockWidth.jsx
  src/components/index.js
  src/hoc/withHtmlAttributes.js
Labels: feature

#1579 Fix: Unit control improvements
  package-lock.json
  package.json
Labels: bug

#1582 Fix: Broken columns in Query block
  src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Labels: bug

#1585 Fix: Bug when using `button` as a `RichText` tag
  src/blocks/text/edit.js
Labels: bug

#1586 Query - Update responsive styles in templates
  package-lock.json
  package.json
  src/blocks/query/templates.js
Labels: refactoring

#1584 Implement new SelectTerms
  includes/class-meta-handler.php
  includes/class-query-utils.php
  package-lock.json
  package.json
  src/blocks/query/components/ControlBuilder.jsx
  src/blocks/query/components/TaxonomyParameterControl.jsx
  src/dynamic-tags/components/DynamicTagSelect.jsx
  src/dynamic-tags/components/SelectTaxonomy.jsx
  src/dynamic-tags/components/SelectTerm.jsx
Labels: feature, Block: Query

#1594 Tweak: Filter local block CSS
  package-lock.json
  package.json
  src/hoc/withStyles.js
Labels: refactoring

#1597 Tweak: Add escaping to HTML attributes
  includes/functions.php
  includes/general.php
Labels: refactoring

#1598 Fix: Loop item bugs
  src/blocks/loop-item/block.json
  src/blocks/loop-item/edit.js
  src/blocks/loop-item/editor.scss
  src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Labels: bug

#1599 Feature: Add inline background control to Loop Item
  src/blocks/loop-item/components/BlockSettings.jsx
Labels: feature

#1600 Tweak: Show Looper appender if empty
  src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Labels: bug

#1601 Tweak: Ensure editor HTML attributes are escaped
  src/hoc/withHtmlAttributes.js
Labels: refactoring

#1602 Feature: Add more CSS properties
  package-lock.json
  package.json
Labels: feature

#1603 Tweak: Remove Container Queries in free
  package-lock.json
  package.json
Labels: refactoring

#1614 Fix: Image block error
  src/hoc/withHtmlAttributes.js
  src/tests/unit/sanitizeHtmlAttribute.test.js
  src/utils/sanitizeHtmlAttribute.js
Labels: bug

#1619 Dynamic Tags - Reduce and cache replacement requests
  includes/dynamic-tags/class-dynamic-tags.php
  src/dynamic-tags/components/DynamicTagBlockToolbar.jsx
  src/dynamic-tags/utils.js
  src/editor/style-html-attribute.js
  src/hoc/withDynamicTag.js
Labels: feature, Dynamic Tags

#1628 Fix: Default button styling
  includes/general.php
Labels: bug
