Repository tomusborne/generateblocks, pull requests merged in 2024-11, with the labels that each got.

#1423 Tweak: Standardize input heights
  package-lock.json
  package.json
  src/components/image-upload/ImageUpload.jsx
  src/components/url-controls/URLControls.jsx
  src/components/url-controls/editor.scss
  src/dynamic-tags/components/DynamicTagModal.jsx
Labels: refactoring

#1425 Tweak: Update styles builder
  package-lock.json
  package.json
  src/blocks/media/components/BlockSettings.jsx
  src/blocks/shape/components/BlockSettings.jsx
Labels: refactoring

#1424 Tweak: Add upgrade menu item
  assets/css/dashboard-global.css
  includes/dashboard.php
Labels: refactoring

#1426 Fix: Dynamic tag returning ID in img src
  includes/dynamic-tags/class-dynamic-tags.php
Labels: bug

#1416 Refactor: Set v1 blocks on update
  includes/class-plugin-update.php
  includes/class-rest.php
  includes/class-settings.php
  includes/dashboard.php
  includes/defaults.php
  includes/functions.php
  includes/general.php
  src/dashboard.js
  src/editor/container-toolbar-appenders.js
  src/editor/disable-blocks.js
  src/extend/block-controls/toolbar-appenders/index.js
  src/settings.js
  src/settings/blocks-version.js
Labels: refactoring

#1428 Refactor: Toolbar appenders
  src/blocks/media/edit.js
  src/blocks/media/index.js
  src/blocks/media/toolbar-appenders.js
  src/blocks/query/edit.js
  src/blocks/query/index.js
  src/blocks/query/toolbar-appenders.js
  src/editor/index.js
  src/editor/toolbar-appenders.js
  src/settings.scss
Labels: refactoring

#1430 Refactor: Use the `inline` block controls group
  src/blocks/text/edit.js
  src/components/link-block-toolbar/LinkBlockToolbar.jsx
  src/editor/button-link-toolbar.js
  src/editor/index.js
  src/editor/toolbar-appenders.js
Labels: refactoring

#1431 Refacto: Remove unused function
  includes/class-dynamic-content.php
  includes/functions.php
Labels: refactoring

#1434 Tweak: Limit blocks that dynamic tags work in
  includes/dynamic-tags/class-dynamic-tags.php
Labels: refactoring

#1433 Refactor: Remove unused packages
  package-lock.json
  package.json
Labels: refactoring

#1436 Feature: Add global max-width button
  package-lock.json
  package.json
  src/editor/global-max-width.js
  src/editor/index.js
Labels: feature

#1437 Fix: Missing `PluginSidebar` before WP 6.6
  src/editor-sidebar/index.js
Labels: bug

#1440 Fix: Dynamic tag select bugs
  src/dynamic-tags/components/DynamicTagSelect.jsx
  src/dynamic-tags/editor.scss
Labels: bug

#1441 Tweak: Remove extra block setting labels
  src/blocks/element/components/BlockSettings.jsx
  src/blocks/element/components/InlineBackgroundImage.jsx
  src/blocks/loop-item/components/BlockSettings.jsx
  src/blocks/looper/components/BlockSettings.jsx
  src/blocks/media/components/BlockSettings.jsx
  src/blocks/query-page-numbers/components/BlockSettings.jsx
  src/blocks/query/components/BlockSettings.jsx
  src/blocks/shape/components/BlockSettings.jsx
  src/blocks/text/components/BlockSettings.jsx
  src/components/image-upload/ImageUpload.jsx
  src/components/url-controls/URLControls.jsx
Labels: refactoring

#1454 Fix: Image editor CSS prefix
  src/blocks/media/components/Image.jsx
  src/blocks/media/components/ImagePlaceholder.jsx
Labels: bug

#1469 Fix: Block transform error
  src/utils/convertLegacyHtmlAttributes.js
Labels: bug

#1470 Tweak: Migrate v1 icon styles
  src/utils/legacyStyleUtils.js
Labels: refactoring

#1471 Tweak: Hide single Query Type
  src/blocks/query/components/QueryInspectorControls.jsx
Labels: refactoring

#1475 Feature: Add pagination type option
  includes/blocks/class-query-page-numbers.php
  includes/blocks/class-query.php
  includes/dynamic-tags/class-dynamic-tags.php
  src/blocks/element/block.json
  src/blocks/query-page-numbers/block.json
  src/blocks/query/block.json
  src/blocks/query/components/QueryInspectorControls.jsx
  src/blocks/query/looper.js
  src/blocks/text/block.json
Labels: feature

#1479 Fix: Error when using an empty Looper block
  includes/blocks/class-looper.php
Labels: bug

#1478 Tweak: Update Query templates
  src/blocks/query/templates.js
Labels: refactoring

#1485 Refactor: Improve how local block styles are set
  package-lock.json
  package.json
  src/components/block-styles-builder/BlockStylesBuilder.jsx
  src/editor/stores.js
  src/hoc/withStyles.js
  src/hooks/useBlockStyles.js
  src/store/block-styles.js
Labels: refactoring

#1490 Tweak: Styles builder tweaks
  package-lock.json
  package.json
  src/hoc/withStyles.js
Labels: bug

#1497 Fix: Allow multiple inner blocks inside the Looper
  includes/blocks/class-looper.php
Labels: bug

#1501 Tweak: Use `useSetStyles`
  package-lock.json
  package.json
  src/hoc/withStyles.js
Labels: refactoring

#1507 Fix: Query posts_per_page when set to -1
  src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Labels: bug

#1503 Add: `generateblocks_default_button_attributes` filter
  .eslintrc.json
  includes/general.php
  src/blocks/text/index.js
Labels: feature

#1508 Update styles builder
  package-lock.json
  package.json
Labels: refactoring

#1510 Tweak: Unify input height in dynamic tag modal
  src/dynamic-tags/editor.scss
Labels: refactoring

#1515 Update styles-builder
  package-lock.json
  package.json
Labels: bug

#1516 Fix query loop paging link issue
  src/blocks/query-page-numbers/block.json
Labels: bug

#1519 Fix: Color picker width
  package-lock.json
  package.json
Labels: bug

#1518 Feature: `{{post_date}}` tag
  includes/dynamic-tags/class-dynamic-tag-callbacks.php
  includes/dynamic-tags/class-dynamic-tags.php
  includes/general.php
  src/blocks/query/templates.js
  src/dynamic-tags/components/DynamicTagSelect.jsx
Labels: feature

#1521 Fix: Query template dates
  src/blocks/query/templates.js
Labels: bug

#1513 Fix dynamic bg images
  package-lock.json
  src/blocks/element/block.json
  src/blocks/element/components/InlineBackgroundImage.jsx
  src/dynamic-tags/utils.js
  src/hoc/withDynamicTag.js
  src/hoc/withHtmlAttributes.js
Labels: bug

#1526 Refactor: Editor styles
  package-lock.json
  package.json
  src/hoc/withStyles.js
Labels: refactoring

#1541 Refactor: Dynamic tag parser
  includes/dynamic-tags/class-register-dynamic-tag.php
Labels: bug, refactoring
