Repository tomusborne/generateblocks, pull requests merged in 2025-01, with the labels that each got.

#1629 Fix: Styles builder element held in memory
  package-lock.json
  package.json
  src/components/block-styles-builder/BlockStylesBuilder.jsx
Labels: bug

#1636 Fix: Broken control
  src/blocks/media/components/BlockSettings.jsx
  src/blocks/query/components/ControlBuilder.jsx
Labels: bug

#1637 Fix: PHP deprecation
  includes/dynamic-tags/class-dynamic-tags.php
Labels: bug

#1638 Fix: Deeply nested queries
  includes/blocks/class-loop-item.php
  includes/blocks/class-looper.php
  includes/blocks/class-query-no-results.php
  includes/blocks/class-query-page-numbers.php
  includes/blocks/class-query.php
  includes/dynamic-tags/class-dynamic-tag-callbacks.php
  includes/dynamic-tags/class-dynamic-tags.php
  src/blocks/element/block.json
  src/blocks/loop-item/block.json
  src/blocks/looper/block.json
  src/blocks/query-no-results/block.json
  src/blocks/query-page-numbers/block.json
  src/blocks/query/block.json
  src/blocks/query/components/QueryInspectorControls.jsx
  src/blocks/query/templates.js
  src/blocks/text/block.json
Labels: bug

#1650 Fix: Styles builder values getting mixed up
  package-lock.json
  package.json
Labels: bug

#1651 Update styles builder
  package-lock.json
  package.json
Labels: bug

#1653 Fix: Styles getting mixed up on atRule
  package-lock.json
  package.json
  src/hoc/withStyles.js
Labels: bug

#1655 Fix: Editor offset with limited posts
  src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Labels: bug

#1657 Packages: Update styles builder
  package-lock.json
  package.json
Labels: bug

#1641 Feature: Legacy Grid block transform
  src/blocks/grid/block.js
  src/blocks/grid/transforms.js
Labels: feature

#1639 Improve: Legacy style transforms
  src/blocks/container/transforms.js
  src/blocks/grid/block.js
  src/blocks/grid/transforms.js
  src/utils/index.js
  src/utils/legacyStyleUtils.js
Labels: refactoring

#1659 Refactor: Improve Layout panel UI
  package-lock.json
  package.json
  src/utils/legacyStyleUtils.js
Labels: refactoring

#1661 Fix: Block transform bugs
  src/blocks/button/transforms.js
  src/utils/legacyStyleUtils.js
Labels: bug

#1663 Fix: Console errors in image block
  src/blocks/media/components/BlockSettings.jsx
Labels: bug

#1664 Tweak: Select Loop Item on context change
  src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Labels: refactoring

#1665 Fix: Pass query data to loop items
  includes/blocks/class-looper.php
Labels: bug

#1674 Fix: Value mismatch when switching at rules
  package-lock.json
  package.json
  src/hoc/withStyles.js
Labels: bug

#1678 Improve: Styles builder indicators
  package-lock.json
  package.json
Labels: refactoring

#1679 Tweak: Add box-sizing to container
  src/blocks/element/block.json
  src/blocks/element/editor.scss
Labels: refactoring

#1680 Improve: Grid transforms
  src/blocks/grid/transforms.js
Labels: refactoring

#1685 Tweak: Add computed style deps to Styles Builder
  package-lock.json
  package.json
  src/components/block-styles-builder/BlockStylesBuilder.jsx
Labels: bug

#1683 Fix: Image styles on transform
  src/blocks/image/transforms.js
Labels: bug

#1686 Improve: Default page numbers template
  src/blocks/query-page-numbers/edit.js
  src/blocks/query/templates.js
Labels: refactoring

#1695 Fix: Allow trailing dynamic tag spaces
  includes/dynamic-tags/class-register-dynamic-tag.php
Labels: bug

#1696 Fix: Border controls inheritance filter
  package-lock.json
  package.json
Labels: bug

#1698 Security: Prevent private post output
  includes/class-dynamic-content.php
Labels: bug

#1700 Tweak: Add v2 free pattern library
  includes/pattern-library/class-libraries.php
Labels: refactoring

#1703 Fix: Allow Element and Text blocks in excerpts
  includes/general.php
Labels: bug

#1704 Tweak: Allow next/prev posts URLs with no Query
  includes/dynamic-tags/class-dynamic-tag-callbacks.php
Labels: bug

#1707 Fix: Multi-selecting image block
  src/blocks/media/edit.js
Labels: bug

#1715 Fix: Post excerpt possible infinite loop
  includes/dynamic-tags/class-dynamic-tag-callbacks.php
Labels: bug

#1716 Fix: Excerpt tag not previewing
  includes/dynamic-tags/class-dynamic-tags.php
  src/dynamic-tags/utils.js
  src/editor/style-html-attribute.js
  src/hoc/withDynamicTag.js
Labels: bug

#1717 Fix: Computed style deps
  package-lock.json
  package.json
  src/components/block-styles-builder/BlockStylesBuilder.jsx
Labels: bug

#1718 Tweak: Simplify post excerpt infinite loop issue
  includes/dynamic-tags/class-dynamic-tag-callbacks.php
  includes/dynamic-tags/class-dynamic-tags.php
  src/dynamic-tags/utils.js
  src/editor/style-html-attribute.js
  src/hoc/withDynamicTag.js
Labels: bug

#1721 Tweak: Handle HTML entities in styles object
  includes/class-enqueue-css.php
  package-lock.json
  package.json
  src/hoc/withStyles.js
Labels: bug

#1722 Fix: Hover style indicators display
  package-lock.json
  package.json
Labels: bug

#1724 Fix: Unique ID regeneration
  package-lock.json
  package.json
Labels: bug

#1727 Fix: Query data memory usage
  includes/blocks/class-loop-item.php
  includes/blocks/class-looper.php
Labels: bug

#1728 Fix: Post permalink not working in Element
  src/blocks/element/block.json
Labels: bug

#1726 Query Preview fixes
  src/blocks/loop-item/block.json
  src/blocks/loop-item/edit.js
  src/blocks/looper/components/LoopInnerBlocksRenderer.jsx
Labels: bug

#1731 Update packages
  package-lock.json
  package.json
Labels: bug

#1732 Fix: Gradient parser
  package-lock.json
  package.json
Labels: bug

#1733 Fix: Show correct at-rule style value in block settings
  src/hoc/withStyles.js
Labels: bug

#1735 Fix: Allow empty gradient stops
  package-lock.json
  package.json
Labels: bug
